In [16]:
pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\bharg\anaconda3\lib\site-packages (3.0.5)
Requirement already satisfied: openpyxl in c:\users\bharg\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\bharg\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\bharg\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [41]:
import pandas as pd
import os

def run_full_pipeline(excel_file, target_images=250):

    food_list = load_and_clean_food_items(excel_file)

    processed_dir = "processed_images"
    os.makedirs(processed_dir, exist_ok=True)

    existing_images = [
        f for f in os.listdir(processed_dir)
        if f.lower().endswith(".jpg")
    ]

    processed_count = len(existing_images)

    print(f"Already processed: {processed_count}")
    print(f"Target: {target_images}")
    print(f"Remaining: {target_images - processed_count}")

    report = []

    for index, food in enumerate(food_list, start=1):

        if processed_count >= target_images:
            print("\nTARGET REACHED!")
            print(f"Total processed images: {processed_count}")
            break

        original_name = food["original_name"]
        search_query = food["search_query"]

        clean_name = sanitize_filename(original_name)

        processed_path = os.path.join(
            processed_dir,
            f"{clean_name}.jpg"
        )

        if os.path.exists(processed_path):

            print(f"\n[{index}] SKIPPED:")
            print(original_name)

            continue

        print("\n" + "=" * 60)
        print(f"PROCESSING")
        print(f"Food: {original_name}")
        print(f"Progress: {processed_count}/{target_images}")
        print("=" * 60)

        raw_path = search_and_download_image(
            search_query
        )

        if raw_path:

            processed_path = process_and_resize_image(
                raw_path,
                original_name
            )

            if processed_path:
                processed_count += 1

                print(
                    f"SUCCESS: {processed_count}/{target_images}"
                )

                report.append({
                    "food_name": original_name,
                    "search_query": search_query,
                    "raw_image": raw_path,
                    "processed_image": processed_path,
                    "status": "SUCCESS"
                })

            else:

                report.append({
                    "food_name": original_name,
                    "search_query": search_query,
                    "raw_image": raw_path,
                    "processed_image": None,
                    "status": "PROCESSING_FAILED"
                })

        else:

            report.append({
                "food_name": original_name,
                "search_query": search_query,
                "raw_image": None,
                "processed_image": None,
                "status": "DOWNLOAD_FAILED"
            })

    if report:

        report_df = pd.DataFrame(report)

        os.makedirs("reports", exist_ok=True)

        report_path = os.path.join(
            "reports",
            "processing_report.xlsx"
        )

        report_df.to_excel(
            report_path,
            index=False
        )

        print(f"\nReport saved to: {report_path}")

    print("\n" + "=" * 60)
    print("PIPELINE STOPPED")
    print("=" * 60)

    print(f"Processed images: {processed_count}")
    print(f"Target: {target_images}")

In [1]:
pip install duckduckgo_search requests

Collecting duckduckgo_search
  Downloading duckduckgo_search-8.1.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: requests in c:\users\bharg\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: click>=8.1.8 in c:\users\bharg\anaconda3\lib\site-packages (from duckduckgo_search) (8.3.3)
Collecting primp>=0.15.0 (from duckduckgo_search)
  Downloading primp-2.0.1-cp310-abi3-win_amd64.whl.metadata (4.0 kB)
Requirement already satisfied: lxml>=5.3.0 in c:\users\bharg\anaconda3\lib\site-packages (from duckduckgo_search) (5.3.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\bharg\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bharg\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\bharg\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bharg\anaconda3\lib\site-packages (from requests) (2025.7.14)
Requirement already satisfied: colorama in c:\users\bharg\anaconda3\lib\site-packages (from click>=8.1.8->duckduckgo_search) (0.4.6)
Downloading duckduckgo_search-8.1.1-py3-none-any.whl (18 kB)
Downloading primp-2.0.1-cp310-abi3-win_amd64.whl (6.4 MB)
   ---------------------------------------- 0.0/6.4 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.4 MB 3.5 MB/s eta 0:00:02
   ---- ----------------------------------- 0.8/6.4 MB 2.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.0/6.4 MB 1.7 MB/s eta 0:00:04
   -------- ------------------------------- 1.3/6.4 MB 1.6 MB/s eta 0:00:04
   ----------- ---------------------------- 1.8/6.4 MB 1.6 MB/s eta 0:00:03
   ------------- -------------------------- 2.1/6.4 MB 1.7 MB/s eta 0:00:03
   ---------------- ----------------------- 2.6/6.4 MB 1.8 MB/s eta 0:00:03
   ------------------- -------------------- 3.1/6.4 MB 1.9 MB/s eta 0:00:02
   ----------------------- ---------------- 3.7/6.4 MB 2.0 MB/s eta 0:00:02
   -------------------------- ------------- 4.2/6.4 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 5.0/6.4 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 6.0/6.4 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 6.4/6.4 MB 2.4 MB/s eta 0:00:00
Installing collected packages: primp, duckduckgo_search

   ---------------------------------------- 2/2 [duckduckgo_search]

Successfully installed duckduckgo_search-8.1.1 primp-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
!pip uninstall -y duckduckgo_search
!pip install -U ddgs

WARNING: Skipping duckduckgo_search as it is not installed.

Requirement already satisfied: ddgs in c:\users\bharg\anaconda3\lib\site-packages (9.16.0)
Requirement already satisfied: click>=8.1.8 in c:\users\bharg\anaconda3\lib\site-packages (from ddgs) (8.3.3)
Requirement already satisfied: primp>=1.3.1 in c:\users\bharg\anaconda3\lib\site-packages (from ddgs) (2.0.1)
Requirement already satisfied: lxml>=4.9.4 in c:\users\bharg\anaconda3\lib\site-packages (from ddgs) (5.3.0)
Requirement already satisfied: colorama in c:\users\bharg\anaconda3\lib\site-packages (from click>=8.1.8->ddgs) (0.4.6)

In [18]:
from ddgs import DDGS

print("DDGS imported successfully")

DDGS imported successfully

In [19]:
from ddgs import DDGS

query = "Chicken Tandoori dish restaurant high quality photo"

with DDGS() as ddgs:
    results = list(ddgs.images(query, max_results=3))

print("Number of results:", len(results))

for result in results:
    print(result.get("image"))

Number of results: 3
https://static.vecteezy.com/system/resources/previews/029/894/950/large_2x/of-tandoori-chicken-as-a-dish-in-a-high-end-restaurant-generative-ai-photo.jpg
https://static.vecteezy.com/system/resources/previews/029/287/405/non_2x/of-tandoori-chicken-as-a-dish-in-a-high-end-restaurant-generative-ai-photo.jpg
https://static.vecteezy.com/system/resources/previews/029/287/410/large_2x/of-tandoori-chicken-as-a-dish-in-a-high-end-restaurant-generative-ai-photo.jpg

In [20]:
import os
import re
import requests
from ddgs import DDGS


def sanitize_filename(filename):
    """Remove characters that are invalid in Windows filenames."""
    return re.sub(r'[\\/*?:"<>|]', "", filename).strip()


def search_and_download_image(
    food_name,
    output_dir="raw_images",
    blur_threshold=80.0
):
    """
    Searches for multiple images, downloads candidates,
    and keeps the first image that passes the sharpness test.
    """

    os.makedirs(output_dir, exist_ok=True)

    clean_name = sanitize_filename(food_name)

    save_path = os.path.join(
        output_dir,
        f"{clean_name}_raw.jpg"
    )

    query = f"{food_name} dish restaurant high quality photo"

    print(f"\nSearching image for: {food_name}...")

    try:

        # Search for 3 image candidates
        with DDGS() as ddgs:
            results = list(
                ddgs.images(
                    query,
                    max_results=3
                )
            )

        if not results:
            print(f"[FAILED] No images found for: {food_name}")
            return None

        # Try each candidate
        for idx, result in enumerate(results, start=1):

            image_url = result.get("image")

            if not image_url:
                continue

            print(f"Trying image {idx}...")

            try:

                # Download candidate
                response = requests.get(
                    image_url,
                    timeout=7,
                    headers={
                        "User-Agent": "Mozilla/5.0"
                    }
                )

                if response.status_code != 200:
                    print(
                        f"[SKIPPED] Image {idx}: "
                        f"HTTP {response.status_code}"
                    )
                    continue

                # Check that the response is actually an image
                content_type = response.headers.get(
                    "Content-Type",
                    ""
                )

                if not content_type.startswith("image/"):
                    print(
                        f"[SKIPPED] Image {idx}: "
                        "not a valid image"
                    )
                    continue

                with open(save_path, "wb") as f:
                    f.write(response.content)

                if not is_image_sharp(
                    save_path,
                    blur_threshold
                ):
                    print(
                        f"[REJECTED] Image {idx} "
                        "is too blurry."
                    )

                    os.remove(save_path)

                    continue

                print(
                    f"[ACCEPTED] Image {idx} "
                    "passed quality check."
                )

                return save_path

            except Exception as e:

                print(
                    f"[SKIPPED] Image {idx} failed: {e}"
                )

                continue

    except Exception as e:

        print(
            f"[ERROR] Search failed for "
            f"{food_name}: {e}"
        )

    print(
        f"[FAILED] No suitable image found "
        f"for {food_name}"
    )

    return None

In [4]:
search_and_download_image("Chicken Tandoori")

Searching image for: Chicken Tandoori...
Trying image 1...
Blur score (higher is sharper): 51.02
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 91.38
[ACCEPTED] Image 2 passed quality check.

'raw_images\\Chicken Tandoori_raw.jpg'

In [5]:
!pip install -U pillow opencv-python

Requirement already satisfied: pillow in c:\users\bharg\anaconda3\lib\site-packages (11.1.0)
Collecting pillow
  Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting opencv-python
  Downloading opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: numpy>=2 in c:\users\bharg\anaconda3\lib\site-packages (from opencv-python) (2.1.3)
Downloading pillow-12.3.0-cp313-cp313-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.2 MB 2.5 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/7.2 MB 2.5 MB/s eta 0:00:03
   ---------- ----------------------------- 1.8/7.2 MB 2.6 MB/s eta 0:00:03
   -------------- ------------------------- 2.6/7.2 MB 2.6 MB/s eta 0:00:02
   ----------------- ---------------------- 3.1/7.2 MB 2.8 MB/s eta 0:00:02
   --------------------- ------------------ 3.9/7.2 MB 2.8 MB/s eta 0:00:02
   -------------------------- ------------- 4.7/7.2 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.2/7.2 MB 3.0 MB/s eta 0:00:01
   ------------------------------- -------- 5.8/7.2 MB 3.0 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 3.0 MB/s eta 0:00:00
Downloading opencv_python-5.0.0.93-cp37-abi3-win_amd64.whl (44.0 MB)
   ---------------------------------------- 0.0/44.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/44.0 MB ? eta -:--:--
    --------------------------------------- 1.0/44.0 MB 2.2 MB/s eta 0:00:20
   - -------------------------------------- 1.3/44.0 MB 2.0 MB/s eta 0:00:21
   - -------------------------------------- 1.6/44.0 MB 2.0 MB/s eta 0:00:22
   - -------------------------------------- 1.6/44.0 MB 2.0 MB/s eta 0:00:22
   - -------------------------------------- 1.8/44.0 MB 1.3 MB/s eta 0:00:32
   - -------------------------------------- 2.1/44.0 MB 1.4 MB/s eta 0:00:30
   -- ------------------------------------- 2.4/44.0 MB 1.3 MB/s eta 0:00:32
   -- ------------------------------------- 2.9/44.0 MB 1.5 MB/s eta 0:00:29
   -- ------------------------------------- 3.1/44.0 MB 1.5 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/44.0 MB 1.5 MB/s eta 0:00:28
   --- ------------------------------------ 3.9/44.0 MB 1.5 MB/s eta 0:00:27
   ---- ----------------------------------- 4.5/44.0 MB 1.6 MB/s eta 0:00:25
   ---- ----------------------------------- 5.0/44.0 MB 1.7 MB/s eta 0:00:24
   ----- ---------------------------------- 5.5/44.0 MB 1.7 MB/s eta 0:00:23
   ----- ---------------------------------- 6.0/44.0 MB 1.8 MB/s eta 0:00:22
   ----- ---------------------------------- 6.6/44.0 MB 1.8 MB/s eta 0:00:21
   ------ --------------------------------- 7.3/44.0 MB 1.9 MB/s eta 0:00:20
   ------- -------------------------------- 8.1/44.0 MB 2.0 MB/s eta 0:00:18
   -------- ------------------------------- 8.9/44.0 MB 2.1 MB/s eta 0:00:17
   --------- ------------------------------ 10.0/44.0 MB 2.2 MB/s eta 0:00:16
   ---------- ----------------------------- 11.0/44.0 MB 2.4 MB/s eta 0:00:15
   ---------- ----------------------------- 11.5/44.0 MB 2.4 MB/s eta 0:00:14
   ----------- ---------------------------- 12.6/44.0 MB 2.5 MB/s eta 0:00:13
   ------------ --------------------------- 13.4/44.0 MB 2.5 MB/s eta 0:00:13
   ------------ --------------------------- 13.6/44.0 MB 2.6 MB/s eta 0:00:12
   ------------ --------------------------- 14.2/44.0 MB 2.5 MB/s eta 0:00:13
   ------------ --------------------------- 14.2/44.0 MB 2.5 MB/s eta 0:00:13
   ------------- -------------------------- 14.4/44.0 MB 2.4 MB/s eta 0:00:13
   ------------- -------------------------- 14.7/44.0 MB 2.3 MB/s eta 0:00:13
   ------------- -------------------------- 14.9/44.0 MB 2.3 MB/s eta 0:00:13
   ------------- -------------------------- 14.9/44.0 MB 2.3 MB/s eta 0:00:13
   ------------- -------------------------- 15.2/44.0 MB 2.2 MB/s eta 0:00:13
   -------------- ------------------------- 15.5/44.0 MB 2.2 MB/s eta 0:00:14
   -------------- ------------------------- 15.7/44.0 MB 2.2 MB/s eta 0:00:14
   -------------- ------------------------- 16.3/44.0 MB 2.1 MB/s eta 0:00:13
   --------------- ------------------------ 16.5/44.0 MB 2.1 MB/s eta 0:00:13
   --------------- ------------------------ 16.8/44.0 MB 2.1 MB/s eta 0:00:13
   --------------- ------------------------ 17.3/44.0 MB 2.1 MB/s eta 0:00:13
   --------------- ------------------------ 17.6/44.0 MB 2.1 MB/s eta 0:00:13
   ---------------- ----------------------- 18.1/44.0 MB 2.1 MB/s eta 0:00:13
   ---------------- ----------------------- 18.6/44.0 MB 2.1 MB/s eta 0:00:13
   ----------------- ---------------------- 18.9/44.0 MB 2.1 MB/s eta 0:00:13
   ----------------- ---------------------- 19.4/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------ --------------------- 19.9/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------ --------------------- 20.4/44.0 MB 2.1 MB/s eta 0:00:12
   ------------------- -------------------- 21.0/44.0 MB 2.1 MB/s eta 0:00:11
   ------------------- -------------------- 21.5/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 22.0/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 22.5/44.0 MB 2.1 MB/s eta 0:00:11
   -------------------- ------------------- 23.1/44.0 MB 2.1 MB/s eta 0:00:10
   --------------------- ------------------ 24.1/44.0 MB 2.2 MB/s eta 0:00:10
   ---------------------- ----------------- 24.6/44.0 MB 2.2 MB/s eta 0:00:09
   ----------------------- ---------------- 25.4/44.0 MB 2.2 MB/s eta 0:00:09
   ----------------------- ---------------- 26.2/44.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 27.0/44.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 27.3/44.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 27.3/44.0 MB 2.3 MB/s eta 0:00:08
   ------------------------- -------------- 27.5/44.0 MB 2.2 MB/s eta 0:00:08
   ------------------------- -------------- 27.8/44.0 MB 2.2 MB/s eta 0:00:08
   ------------------------- -------------- 28.0/44.0 MB 2.2 MB/s eta 0:00:08
   ------------------------- -------------- 28.3/44.0 MB 2.2 MB/s eta 0:00:08
   -------------------------- ------------- 28.8/44.0 MB 2.2 MB/s eta 0:00:07
   -------------------------- ------------- 29.1/44.0 MB 2.2 MB/s eta 0:00:07
   -------------------------- ------------- 29.6/44.0 MB 2.2 MB/s eta 0:00:07
   --------------------------- ------------ 30.1/44.0 MB 2.2 MB/s eta 0:00:07
   --------------------------- ------------ 30.7/44.0 MB 2.2 MB/s eta 0:00:07
   ---------------------------- ----------- 30.9/44.0 MB 2.2 MB/s eta 0:00:07
   ---------------------------- ----------- 31.5/44.0 MB 2.2 MB/s eta 0:00:06
   ---------------------------- ----------- 31.7/44.0 MB 2.2 MB/s eta 0:00:06
   ----------------------------- ---------- 32.5/44.0 MB 2.2 MB/s eta 0:00:06
   ------------------------------ --------- 33.0/44.0 MB 2.2 MB/s eta 0:00:06
   ------------------------------ --------- 33.3/44.0 MB 2.2 MB/s eta 0:00:05
   ------------------------------ --------- 33.8/44.0 MB 2.2 MB/s eta 0:00:05
   ------------------------------- -------- 34.3/44.0 MB 2.2 MB/s eta 0:00:05
   ------------------------------- -------- 35.1/44.0 MB 2.2 MB/s eta 0:00:05
   -------------------------------- ------- 35.7/44.0 MB 2.2 MB/s eta 0:00:04
   --------------------------------- ------ 36.4/44.0 MB 2.2 MB/s eta 0:00:04
   --------------------------------- ------ 37.2/44.0 MB 2.2 MB/s eta 0:00:04
   ---------------------------------- ----- 38.0/44.0 MB 2.3 MB/s eta 0:00:03
   ----------------------------------- ---- 38.8/44.0 MB 2.3 MB/s eta 0:00:03
   ----------------------------------- ---- 39.3/44.0 MB 2.3 MB/s eta 0:00:03
   ----------------------------------- ---- 39.6/44.0 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 40.1/44.0 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 40.4/44.0 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 40.6/44.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------ --- 40.6/44.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 40.9/44.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 41.2/44.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 41.4/44.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 41.7/44.0 MB 2.2 MB/s eta 0:00:02
   -------------------------------------- - 41.9/44.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 42.2/44.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 42.5/44.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 42.7/44.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  43.0/44.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  43.3/44.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  43.5/44.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 44.0/44.0 MB 2.1 MB/s eta 0:00:00
Installing collected packages: pillow, opencv-python

  Attempting uninstall: pillow

    Found existing installation: pillow 11.1.0

    Uninstalling pillow-11.1.0:

      Successfully uninstalled pillow-11.1.0

   ---------------------------------------- 0/2 [pillow]
   ---------------------------------------- 0/2 [pillow]
   ---------------------------------------- 0/2 [pillow]
   ---------------------------------------- 0/2 [pillow]
   -------------------- ------------------- 1/2 [opencv-python]
   -------------------- ------------------- 1/2 [opencv-python]
   -------------------- ------------------- 1/2 [opencv-python]
   -------------------- ------------------- 1/2 [opencv-python]
   ---------------------------------------- 2/2 [opencv-python]

Successfully installed opencv-python-5.0.0.93 pillow-12.3.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pillow<12,>=7.1.0, but you have pillow 12.3.0 which is incompatible.

In [21]:
from PIL import Image
import cv2

print("Image processing tools are working!")

Image processing tools are working!

In [22]:
import os
import cv2
from PIL import Image, ImageOps

def is_image_sharp(image_path, blur_threshold=80.0):
    """Calculates Laplacian variance to detect if an image is too blurry."""
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        return False
    variance = cv2.Laplacian(img, cv2.CV_64F).var()
    print(f"Blur score (higher is sharper): {variance:.2f}")
    return variance >= blur_threshold

import os
from PIL import Image, ImageOps


def process_and_resize_image(
    input_path,
    food_name,
    output_dir="processed_images",
    target_size=(1800, 1200)
):
    """
    Resizes, center-crops, and compresses an image
    to 1800x1200 and keeps it under 10 MB.
    """

    os.makedirs(output_dir, exist_ok=True)

    clean_name = sanitize_filename(food_name)

    save_path = os.path.join(
        output_dir,
        f"{clean_name}.jpg"
    )

    try:

        with Image.open(input_path) as img:

            print(f"Original size: {img.size}")

            # Convert image to RGB
            if img.mode != "RGB":
                img = img.convert("RGB")

            # Resize + center crop
            processed_img = ImageOps.fit(
                img,
                target_size,
                Image.Resampling.LANCZOS,
                centering=(0.5, 0.5)
            )

            print(
                f"Processed size: {processed_img.size}"
            )

            # Start with high JPEG quality
            quality = 90

            processed_img.save(
                save_path,
                "JPEG",
                quality=quality,
                optimize=True
            )

            while (
                os.path.getsize(save_path)
                > 10 * 1024 * 1024
                and quality > 10
            ):

                quality -= 5

                processed_img.save(
                    save_path,
                    "JPEG",
                    quality=quality,
                    optimize=True
                )

            file_size_mb = (
                os.path.getsize(save_path)
                / (1024 * 1024)
            )

            print(
                f"[PROCESSED & SAVED] {save_path}"
            )

            print(
                f"Final size: "
                f"{processed_img.size[0]} × "
                f"{processed_img.size[1]} pixels"
            )

            print(
                f"File size: {file_size_mb:.2f} MB"
            )

            return save_path

    except Exception as e:

        print(
            f"[ERROR] Failed to process "
            f"'{food_name}': {e}"
        )

        return None

if __name__ == "__main__":
    raw_path = "raw_images/Chicken Tandoori_raw.jpg"
    if os.path.exists(raw_path):
        process_and_resize_image(raw_path, "Chicken Tandoori")

Original size: (3497, 1960)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

In [23]:
process_and_resize_image(
    raw_path,
    "Chicken Tandoori"
)

Original size: (3497, 1960)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

'processed_images\\Chicken Tandoori.jpg'

In [9]:
!pip install -U pandas openpyxl

Requirement already satisfied: pandas in c:\users\bharg\anaconda3\lib\site-packages (2.2.3)
Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: openpyxl in c:\users\bharg\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\bharg\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\bharg\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\bharg\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 1.3 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.8 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.8 MB 1.2 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/9.8 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.8 MB 1.3 MB/s eta 0:00:07
   ------- -------------------------------- 1.8/9.8 MB 1.3 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/9.8 MB 1.3 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.8 MB 1.3 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.8 MB 1.4 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.4 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.8 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.5 MB/s eta 0:00:05
   ----------------- ---------------------- 4.2/9.8 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.4 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.5 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.5 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.8 MB 1.5 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 1.5 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.5 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.8 MB 1.4 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.4 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.8 MB 1.4 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.8 MB 1.5 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.5 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.8 MB 1.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.8 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.5 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
Successfully installed pandas-3.0.5

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.5 which is incompatible.
streamlit 1.45.1 requires pillow<12,>=7.1.0, but you have pillow 12.3.0 which is incompatible.

In [10]:
!pip install -U google-api-python-client google-auth-httplib2 google-auth-oauthlib

Collecting google-api-python-client
  Downloading google_api_python_client-2.200.0-py3-none-any.whl.metadata (6.8 kB)
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.4.2-py3-none-any.whl.metadata (3.0 kB)
Collecting google-auth-oauthlib
  Downloading google_auth_oauthlib-1.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting httplib2<1.0.0,>=0.19.0 (from google-api-python-client)
  Downloading httplib2-0.32.0-py3-none-any.whl.metadata (2.2 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 (from google-api-python-client)
  Downloading google_auth-2.58.0-py3-none-any.whl.metadata (6.0 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client)
  Downloading google_api_core-2.37.0-py3-none-any.whl.metadata (3.2 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.69.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading googleapis_common_protos-1.75.3-py3-none-any.whl.metadata (8.5 kB)
Collecting protobuf<8.0.0,>=6.33.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading protobuf-7.36.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting proto-plus<2.0.0,>=1.26.1 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading proto_plus-1.28.4-py3-none-any.whl.metadata (2.2 kB)
Collecting requests<3.0.0,>=2.33.0 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting opentelemetry-api<2.0.0,>=1.44.0 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client)
  Downloading opentelemetry_api-1.44.0-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\bharg\anaconda3\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\bharg\anaconda3\lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (44.0.1)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\bharg\anaconda3\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.2.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\bharg\anaconda3\lib\site-packages (from opentelemetry-api<2.0.0,>=1.44.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (4.12.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\bharg\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\bharg\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\bharg\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.3.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\bharg\anaconda3\lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2025.7.14)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: cffi>=1.12 in c:\users\bharg\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (1.17.1)
Requirement already satisfied: pycparser in c:\users\bharg\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (2.21)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\bharg\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.8)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Downloading oauthlib-3.3.1-py3-none-any.whl.metadata (7.9 kB)
Downloading google_api_python_client-2.200.0-py3-none-any.whl (16.1 MB)
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
    --------------------------------------- 0.3/16.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.1 MB 1.3 MB/s eta 0:00:13
   - -------------------------------------- 0.5/16.1 MB 1.3 MB/s eta 0:00:13
   - -------------------------------------- 0.8/16.1 MB 844.6 kB/s eta 0:00:19
   -- ------------------------------------- 1.0/16.1 MB 1.1 MB/s eta 0:00:15
   --- ------------------------------------ 1.3/16.1 MB 1.1 MB/s eta 0:00:14
   --- ------------------------------------ 1.6/16.1 MB 1.1 MB/s eta 0:00:14
   ---- ----------------------------------- 1.8/16.1 MB 1.1 MB/s eta 0:00:13
   ----- ---------------------------------- 2.1/16.1 MB 1.2 MB/s eta 0:00:12
   ----- ---------------------------------- 2.4/16.1 MB 1.2 MB/s eta 0:00:12
   ------ --------------------------------- 2.6/16.1 MB 1.2 MB/s eta 0:00:12
   ------- -------------------------------- 2.9/16.1 MB 1.2 MB/s eta 0:00:11
   ------- -------------------------------- 3.1/16.1 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.7/16.1 MB 1.3 MB/s eta 0:00:10
   --------- ------------------------------ 3.9/16.1 MB 1.3 MB/s eta 0:00:10
   ---------- ----------------------------- 4.2/16.1 MB 1.3 MB/s eta 0:00:10
   ----------- ---------------------------- 4.5/16.1 MB 1.3 MB/s eta 0:00:10
   ----------- ---------------------------- 4.7/16.1 MB 1.3 MB/s eta 0:00:09
   ------------ --------------------------- 5.0/16.1 MB 1.3 MB/s eta 0:00:09
   ------------- -------------------------- 5.2/16.1 MB 1.3 MB/s eta 0:00:09
   ------------- -------------------------- 5.5/16.1 MB 1.3 MB/s eta 0:00:09
   ------------- -------------------------- 5.5/16.1 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 5.8/16.1 MB 1.2 MB/s eta 0:00:09
   -------------- ------------------------- 6.0/16.1 MB 1.2 MB/s eta 0:00:09
   --------------- ------------------------ 6.3/16.1 MB 1.2 MB/s eta 0:00:08
   ---------------- ----------------------- 6.6/16.1 MB 1.2 MB/s eta 0:00:08
   ---------------- ----------------------- 6.8/16.1 MB 1.2 MB/s eta 0:00:08
   ----------------- ---------------------- 7.1/16.1 MB 1.2 MB/s eta 0:00:08
   ------------------ --------------------- 7.3/16.1 MB 1.2 MB/s eta 0:00:08
   ------------------ --------------------- 7.6/16.1 MB 1.2 MB/s eta 0:00:07
   ------------------- -------------------- 7.9/16.1 MB 1.3 MB/s eta 0:00:07
   ------------------- -------------------- 7.9/16.1 MB 1.3 MB/s eta 0:00:07
   -------------------- ------------------- 8.1/16.1 MB 1.2 MB/s eta 0:00:07
   -------------------- ------------------- 8.4/16.1 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.7/16.1 MB 1.2 MB/s eta 0:00:07
   --------------------- ------------------ 8.7/16.1 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 8.9/16.1 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 8.9/16.1 MB 1.2 MB/s eta 0:00:07
   ---------------------- ----------------- 9.2/16.1 MB 1.1 MB/s eta 0:00:07
   ----------------------- ---------------- 9.4/16.1 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.7/16.1 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 9.7/16.1 MB 1.1 MB/s eta 0:00:06
   ------------------------ --------------- 10.0/16.1 MB 1.1 MB/s eta 0:00:06
   ------------------------- -------------- 10.2/16.1 MB 1.1 MB/s eta 0:00:06
   ------------------------- -------------- 10.2/16.1 MB 1.1 MB/s eta 0:00:06
   -------------------------- ------------- 10.5/16.1 MB 1.1 MB/s eta 0:00:06
   -------------------------- ------------- 10.7/16.1 MB 1.1 MB/s eta 0:00:05
   --------------------------- ------------ 11.0/16.1 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 11.3/16.1 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 11.5/16.1 MB 1.1 MB/s eta 0:00:05
   ----------------------------- ---------- 11.8/16.1 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 12.1/16.1 MB 1.1 MB/s eta 0:00:04
   ------------------------------- -------- 12.6/16.1 MB 1.1 MB/s eta 0:00:04
   ------------------------------- -------- 12.8/16.1 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 13.1/16.1 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 13.1/16.1 MB 1.1 MB/s eta 0:00:03
   -------------------------------- ------- 13.1/16.1 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 13.4/16.1 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 13.6/16.1 MB 1.1 MB/s eta 0:00:03
   --------------------------------- ------ 13.6/16.1 MB 1.1 MB/s eta 0:00:03
   ---------------------------------- ----- 13.9/16.1 MB 1.1 MB/s eta 0:00:03
   ---------------------------------- ----- 13.9/16.1 MB 1.1 MB/s eta 0:00:03
   ----------------------------------- ---- 14.2/16.1 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 14.2/16.1 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 14.4/16.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 14.7/16.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 14.7/16.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 14.9/16.1 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 15.2/16.1 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 15.2/16.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 15.5/16.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  15.7/16.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  16.0/16.1 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 16.1/16.1 MB 1.1 MB/s eta 0:00:00
Downloading google_auth_httplib2-0.4.2-py3-none-any.whl (9.5 kB)
Downloading google_api_core-2.37.0-py3-none-any.whl (186 kB)
Downloading google_auth-2.58.0-py3-none-any.whl (262 kB)
Downloading googleapis_common_protos-1.75.3-py3-none-any.whl (306 kB)
Downloading httplib2-0.32.0-py3-none-any.whl (93 kB)
Downloading opentelemetry_api-1.44.0-py3-none-any.whl (60 kB)
Downloading proto_plus-1.28.4-py3-none-any.whl (50 kB)
Downloading protobuf-7.36.1-cp310-abi3-win_amd64.whl (456 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Downloading google_auth_oauthlib-1.4.1-py3-none-any.whl (19 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Installing collected packages: uritemplate, requests, protobuf, opentelemetry-api, oauthlib, httplib2, requests-oauthlib, proto-plus, googleapis-common-protos, google-auth, google-auth-oauthlib, google-auth-httplib2, google-api-core, google-api-python-client

  Attempting uninstall: requests

    Found existing installation: requests 2.32.3

    Uninstalling requests-2.32.3:

      Successfully uninstalled requests-2.32.3

   -- -------------------------------------  1/14 [requests]
  Attempting uninstall: protobuf
   -- -------------------------------------  1/14 [requests]
    Found existing installation: protobuf 5.29.3
   -- -------------------------------------  1/14 [requests]
    Uninstalling protobuf-5.29.3:
   -- -------------------------------------  1/14 [requests]
      Successfully uninstalled protobuf-5.29.3
   -- -------------------------------------  1/14 [requests]
   ----- ----------------------------------  2/14 [protobuf]
   ----- ----------------------------------  2/14 [protobuf]
   -------- -------------------------------  3/14 [opentelemetry-api]
   ----------- ----------------------------  4/14 [oauthlib]
   ----------- ----------------------------  4/14 [oauthlib]
   ----------- ----------------------------  4/14 [oauthlib]
   -------------------- -------------------  7/14 [proto-plus]
   ---------------------- -----------------  8/14 [googleapis-common-protos]
   ---------------------- -----------------  8/14 [googleapis-common-protos]
   ------------------------- --------------  9/14 [google-auth]
   ------------------------- --------------  9/14 [google-auth]
   ------------------------- --------------  9/14 [google-auth]
   ---------------------------------- ----- 12/14 [google-api-core]
   ---------------------------------- ----- 12/14 [google-api-core]
   ------------------------------------- -- 13/14 [google-api-python-client]
   ------------------------------------- -- 13/14 [google-api-python-client]
   ------------------------------------- -- 13/14 [google-api-python-client]
   ------------------------------------- -- 13/14 [google-api-python-client]
   ------------------------------------- -- 13/14 [google-api-python-client]
   ---------------------------------------- 14/14 [google-api-python-client]

Successfully installed google-api-core-2.37.0 google-api-python-client-2.200.0 google-auth-2.58.0 google-auth-httplib2-0.4.2 google-auth-oauthlib-1.4.1 googleapis-common-protos-1.75.3 httplib2-0.32.0 oauthlib-3.3.1 opentelemetry-api-1.44.0 proto-plus-1.28.4 protobuf-7.36.1 requests-2.34.2 requests-oauthlib-2.0.0 uritemplate-4.2.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.5 which is incompatible.
streamlit 1.45.1 requires pillow<12,>=7.1.0, but you have pillow 12.3.0 which is incompatible.
streamlit 1.45.1 requires protobuf<7,>=3.20, but you have protobuf 7.36.1 which is incompatible.

In [24]:
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials

print("Google Drive libraries are working!")

Google Drive libraries are working!

In [25]:
import pandas as pd
import os


def run_food_image_pipeline(excel_file):

    # -----------------------------------------
    # STEP 1: Load food items from Excel
    # -----------------------------------------

    food_list = load_and_clean_food_items(excel_file)

    print(f"\nTotal food items found: {len(food_list)}")

    report = []

    # -----------------------------------------
    # STEP 2: Process each food item
    # -----------------------------------------

    for index, food in enumerate(food_list, start=1):

        original_name = food["original_name"]
        search_query = food["search_query"]

        print("\n" + "=" * 60)
        print(f"PROCESSING {index}/{len(food_list)}")
        print(f"Food: {original_name}")
        print("=" * 60)

        raw_path = None
        processed_path = None
        status = "FAILED"

        # -----------------------------------------
        # STEP 3: Search and download
        # -----------------------------------------

        raw_path = search_and_download_image(
            search_query
        )

        if raw_path:

            # -----------------------------------------
            # STEP 4: Process image
            # -----------------------------------------

            processed_path = process_and_resize_image(
                raw_path,
                original_name
            )

            if processed_path:
                status = "SUCCESS"

        # -----------------------------------------
        # STEP 5: Add result to report
        # -----------------------------------------

        report.append({
            "food_name": original_name,
            "search_query": search_query,
            "raw_image": raw_path,
            "processed_image": processed_path,
            "status": status
        })

    # -----------------------------------------
    # STEP 6: Create report
    # -----------------------------------------

    report_df = pd.DataFrame(report)

    os.makedirs("reports", exist_ok=True)

    report_path = os.path.join(
        "reports",
        "processing_report.xlsx"
    )

    report_df.to_excel(
        report_path,
        index=False
    )

    # -----------------------------------------
    # STEP 7: Summary
    # -----------------------------------------

    successful = sum(
        report_df["status"] == "SUCCESS"
    )

    failed = sum(
        report_df["status"] == "FAILED"
    )

    print("\n" + "=" * 60)
    print("PIPELINE COMPLETE")
    print("=" * 60)

    print(f"Total items : {len(report_df)}")
    print(f"Successful  : {successful}")
    print(f"Failed      : {failed}")

    print(f"\nReport saved to:")
    print(report_path)

    return report_df

In [34]:
excel_file = r"C:\Users\Bharg\Downloads\Assignment - Ai agent  - Sheet1.xlsx"

In [29]:
food_list = load_and_clean_food_items(excel_file)

print("First 3 items:")
print(food_list[:3])

First 3 items:
[{'original_name': 'Chicken Tandoori', 'search_query': 'Chicken Tandoori'}, {'original_name': 'Veg Fried Rice', 'search_query': 'Veg Fried Rice'}, {'original_name': 'Chicken Biryani Boneless', 'search_query': 'Chicken Biryani Boneless'}]

In [30]:
def process_test_food_items(excel_file, number_of_items=3):

    food_list = load_and_clean_food_items(excel_file)

    test_list = food_list[:number_of_items]

    print(f"\nTesting {len(test_list)} food items...")

    for index, food in enumerate(test_list, start=1):

        original_name = food["original_name"]
        search_query = food["search_query"]

        print("\n" + "=" * 60)
        print(f"PROCESSING {index}/{len(test_list)}")
        print(f"Food: {original_name}")
        print("=" * 60)

        # --------------------------------
        # SEARCH + DOWNLOAD
        # --------------------------------

        raw_path = search_and_download_image(
            search_query
        )

        # --------------------------------
        # RESIZE + CROP + COMPRESS
        # --------------------------------

        if raw_path:

            processed_path = process_and_resize_image(
                raw_path,
                original_name
            )

            if processed_path:

                print(
                    f"[COMPLETE] {original_name}"
                )

            else:

                print(
                    f"[FAILED] Processing: "
                    f"{original_name}"
                )

        else:

            print(
                f"[FAILED] Downloading: "
                f"{original_name}"
            )

In [32]:
process_test_food_items(
    excel_file,
    number_of_items=3
)

Testing 3 food items...

============================================================
PROCESSING 1/3
Food: Chicken Tandoori
============================================================

Searching image for: Chicken Tandoori...
Trying image 1...
Blur score (higher is sharper): 51.02
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 91.38
[ACCEPTED] Image 2 passed quality check.
Original size: (3497, 1960)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB
[COMPLETE] Chicken Tandoori

============================================================
PROCESSING 2/3
Food: Veg Fried Rice
============================================================

Searching image for: Veg Fried Rice...
Trying image 1...
Blur score (higher is sharper): 126.79
[ACCEPTED] Image 1 passed quality check.
Original size: (1050, 700)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.27 MB
[COMPLETE] Veg Fried Rice

============================================================
PROCESSING 3/3
Food: Chicken Biryani Boneless
============================================================

Searching image for: Chicken Biryani Boneless...
Trying image 1...
Blur score (higher is sharper): 372.77
[ACCEPTED] Image 1 passed quality check.
Original size: (1393, 1504)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Biryani Boneless.jpg
Final size: 1800 × 1200 pixels
File size: 0.58 MB
[COMPLETE] Chicken Biryani Boneless

In [36]:
def run_full_pipeline(excel_file):

    food_list = load_and_clean_food_items(excel_file)

    print(f"\nTotal food items: {len(food_list)}")

    report = []

    for index, food in enumerate(food_list, start=1):

        original_name = food["original_name"]
        search_query = food["search_query"]

        print("\n" + "=" * 60)
        print(f"PROCESSING {index}/{len(food_list)}")
        print(f"Food: {original_name}")
        print("=" * 60)

        raw_path = None
        processed_path = None
        status = "FAILED"

        raw_path = search_and_download_image(
            search_query
        )

        if raw_path:

            processed_path = process_and_resize_image(
                raw_path,
                original_name
            )

            if processed_path:
                status = "SUCCESS"

        report.append({
            "food_name": original_name,
            "search_query": search_query,
            "raw_image": raw_path,
            "processed_image": processed_path,
            "status": status
        })

    report_df = pd.DataFrame(report)

    os.makedirs("reports", exist_ok=True)

    report_path = os.path.join(
        "reports",
        "processing_report.xlsx"
    )

    report_df.to_excel(
        report_path,
        index=False
    )

    successful = (
        report_df["status"] == "SUCCESS"
    ).sum()

    failed = (
        report_df["status"] == "FAILED"
    ).sum()

    print("\n" + "=" * 60)
    print("PIPELINE COMPLETE")
    print("=" * 60)

    print(f"Total     : {len(report_df)}")
    print(f"Successful: {successful}")
    print(f"Failed    : {failed}")

    print(f"\nReport:")
    print(report_path)

    return report_df

In [35]:
report_df = run_full_pipeline(excel_file)

Total food items: 420

============================================================
PROCESSING 1/420
Food: Chicken Tandoori
============================================================

Searching image for: Chicken Tandoori...
Trying image 1...
Blur score (higher is sharper): 51.02
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 526.42
[ACCEPTED] Image 2 passed quality check.
Original size: (1749, 980)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.37 MB

============================================================
PROCESSING 2/420
Food: Veg Fried Rice
============================================================

Searching image for: Veg Fried Rice...
Trying image 1...
Blur score (higher is sharper): 126.79
[ACCEPTED] Image 1 passed quality check.
Original size: (1050, 700)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.27 MB

============================================================
PROCESSING 3/420
Food: Chicken Biryani Boneless
============================================================

Searching image for: Chicken Biryani Boneless...
Trying image 1...
Blur score (higher is sharper): 372.77
[ACCEPTED] Image 1 passed quality check.
Original size: (1393, 1504)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Biryani Boneless.jpg
Final size: 1800 × 1200 pixels
File size: 0.58 MB

============================================================
PROCESSING 4/420
Food: Butter Roti
============================================================

Searching image for: Butter Roti...
Trying image 1...
Blur score (higher is sharper): 123.01
[ACCEPTED] Image 1 passed quality check.
Original size: (2048, 2048)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Butter Roti.jpg
Final size: 1800 × 1200 pixels
File size: 0.37 MB

============================================================
PROCESSING 5/420
Food: Paneer Tikka Masala
============================================================

Searching image for: Paneer Tikka Masala...
Trying image 1...
Blur score (higher is sharper): 950.16
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Tikka Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.42 MB

============================================================
PROCESSING 6/420
Food: Chicken Fried Rice
============================================================

Searching image for: Chicken Fried Rice...
Trying image 1...
Blur score (higher is sharper): 224.28
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 1129)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.34 MB

============================================================
PROCESSING 7/420
Food: Veg Triple Schezwan Fried Rice
============================================================

Searching image for: Veg Triple Schezwan Fried Rice...
Trying image 1...
Blur score (higher is sharper): 101.58
[ACCEPTED] Image 1 passed quality check.
Original size: (2560, 1705)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Triple Schezwan Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.44 MB

============================================================
PROCESSING 8/420
Food: Roti
============================================================

Searching image for: Roti...
Trying image 1...
Blur score (higher is sharper): 196.26
[ACCEPTED] Image 1 passed quality check.
Original size: (1749, 980)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Roti.jpg
Final size: 1800 × 1200 pixels
File size: 0.31 MB

============================================================
PROCESSING 9/420
Food: Chicken Tandoori
============================================================

Searching image for: Chicken Tandoori...
Trying image 1...
Blur score (higher is sharper): 51.02
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 526.42
[ACCEPTED] Image 2 passed quality check.
Original size: (1749, 980)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.37 MB

============================================================
PROCESSING 10/420
Food: Dal Khichdi Tadka Chicken Triple Fried Rice
============================================================

Searching image for: Dal Khichdi Tadka Chicken Triple Fried Rice...
Trying image 1...
Blur score (higher is sharper): 708.61
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1003)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Dal Khichdi Tadka Chicken Triple Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.33 MB

============================================================
PROCESSING 11/420
Food: Chicken Lollipop
============================================================

Searching image for: Chicken Lollipop...
Trying image 1...
Blur score (higher is sharper): 511.07
[ACCEPTED] Image 1 passed quality check.
Original size: (1440, 1080)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Lollipop.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB

============================================================
PROCESSING 12/420
Food: Naan
============================================================

Searching image for: Naan...
Trying image 1...
Blur score (higher is sharper): 238.40
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 2000)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Naan.jpg
Final size: 1800 × 1200 pixels
File size: 0.38 MB

============================================================
PROCESSING 13/420
Food: Chicken Chilli Chicken Kala Masala
============================================================

Searching image for: Chicken Chilli Chicken Kala Masala...
Trying image 1...
Blur score (higher is sharper): 1824.93
[ACCEPTED] Image 1 passed quality check.
Original size: (900, 897)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Chilli Chicken Kala Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.51 MB

============================================================
PROCESSING 14/420
Food: Dal Tadka
============================================================

Searching image for: Dal Tadka...
Trying image 1...
Blur score (higher is sharper): 704.00
[ACCEPTED] Image 1 passed quality check.
Original size: (1249, 700)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Dal Tadka.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB

============================================================
PROCESSING 15/420
Food: Paneer Crispy
============================================================

Searching image for: Paneer Crispy...
Trying image 1...
Blur score (higher is sharper): 249.05
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 576)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Crispy.jpg
Final size: 1800 × 1200 pixels
File size: 0.36 MB

============================================================
PROCESSING 16/420
Food: Butter Naan Chicken Crispy
============================================================

Searching image for: Butter Naan Chicken Crispy...
Trying image 1...
Blur score (higher is sharper): 1988.71
[ACCEPTED] Image 1 passed quality check.
Original size: (960, 1200)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Butter Naan Chicken Crispy.jpg
Final size: 1800 × 1200 pixels
File size: 0.59 MB

============================================================
PROCESSING 17/420
Food: Chicken Masala Boneless
============================================================

Searching image for: Chicken Masala Boneless...
Trying image 1...
Blur score (higher is sharper): 791.69
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Masala Boneless.jpg
Final size: 1800 × 1200 pixels
File size: 0.48 MB

============================================================
PROCESSING 18/420
Food: Chicken Tandoori
============================================================

Searching image for: Chicken Tandoori...
Trying image 1...
Blur score (higher is sharper): 51.02
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 91.38
[ACCEPTED] Image 2 passed quality check.
Original size: (3497, 1960)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

============================================================
PROCESSING 19/420
Food: Veg Handi
============================================================

Searching image for: Veg Handi...
Trying image 1...
Blur score (higher is sharper): 301.08
[ACCEPTED] Image 1 passed quality check.
Original size: (1200, 800)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Handi.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB

============================================================
PROCESSING 20/420
Food: Veg Dum Biryani
============================================================

Searching image for: Veg Dum Biryani...
Trying image 1...
Blur score (higher is sharper): 46.39
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 167.22
[ACCEPTED] Image 2 passed quality check.
Original size: (2000, 1500)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Dum Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB

============================================================
PROCESSING 21/420
Food: Chicken Tikka Biryani
============================================================

Searching image for: Chicken Tikka Biryani...
Trying image 1...
[SKIPPED] Image 1: HTTP 403
Trying image 2...
Blur score (higher is sharper): 825.16
[ACCEPTED] Image 2 passed quality check.
Original size: (960, 1200)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tikka Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.56 MB

============================================================
PROCESSING 22/420
Food: Veg Manchurian
============================================================

Searching image for: Veg Manchurian...
Trying image 1...
Blur score (higher is sharper): 1035.47
[ACCEPTED] Image 1 passed quality check.
Original size: (1480, 986)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Manchurian.jpg
Final size: 1800 × 1200 pixels
File size: 0.48 MB

============================================================
PROCESSING 23/420
Food: Kulcha
============================================================

Searching image for: Kulcha...
Trying image 1...
Blur score (higher is sharper): 721.03
[ACCEPTED] Image 1 passed quality check.
Original size: (1400, 788)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Kulcha.jpg
Final size: 1800 × 1200 pixels
File size: 0.22 MB

============================================================
PROCESSING 24/420
Food: Veg Kolhapuri
============================================================

Searching image for: Veg Kolhapuri...
Trying image 1...
Blur score (higher is sharper): 387.15
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 769)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Kolhapuri.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

============================================================
PROCESSING 25/420
Food: Chicken Schezwan Fried Rice
============================================================

Searching image for: Chicken Schezwan Fried Rice...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
[SKIPPED] Image 2: not a valid image
Trying image 3...
Blur score (higher is sharper): 677.58
[ACCEPTED] Image 3 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Schezwan Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.49 MB

============================================================
PROCESSING 26/420
Food: Paneer Kolhapuri
============================================================

Searching image for: Paneer Kolhapuri...
Trying image 1...
Blur score (higher is sharper): 934.41
[ACCEPTED] Image 1 passed quality check.
Original size: (1280, 958)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Kolhapuri.jpg
Final size: 1800 × 1200 pixels
File size: 0.56 MB

============================================================
PROCESSING 27/420
Food: Paneer Makhanwala
============================================================

Searching image for: Paneer Makhanwala...
Trying image 1...
Blur score (higher is sharper): 277.79
[ACCEPTED] Image 1 passed quality check.
Original size: (670, 1001)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Makhanwala.jpg
Final size: 1800 × 1200 pixels
File size: 0.27 MB

============================================================
PROCESSING 28/420
Food: Chicken KL Special Soup
============================================================

Searching image for: Chicken KL Special Soup...
Trying image 1...
Blur score (higher is sharper): 14.71
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 65.63
[REJECTED] Image 2 is too blurry.
Trying image 3...
Blur score (higher is sharper): 182.15
[ACCEPTED] Image 3 passed quality check.
Original size: (1080, 1080)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken KL Special Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.32 MB

============================================================
PROCESSING 29/420
Food: Chicken Lollipop Tandoori
============================================================

Searching image for: Chicken Lollipop Tandoori...
Trying image 1...
Blur score (higher is sharper): 105.96
[ACCEPTED] Image 1 passed quality check.
Original size: (2937, 1960)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Lollipop Tandoori.jpg
Final size: 1800 × 1200 pixels
File size: 0.36 MB

============================================================
PROCESSING 30/420
Food: Jeera Rice
============================================================

Searching image for: Jeera Rice...
Trying image 1...
Blur score (higher is sharper): 244.45
[ACCEPTED] Image 1 passed quality check.
Original size: (1200, 1800)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Jeera Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

============================================================
PROCESSING 31/420
Food: Veg Manchow Soup Veg Crispy
============================================================

Searching image for: Veg Manchow Soup Veg Crispy...
Trying image 1...
Blur score (higher is sharper): 58.49
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 342.52
[ACCEPTED] Image 2 passed quality check.
Original size: (800, 1200)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Manchow Soup Veg Crispy.jpg
Final size: 1800 × 1200 pixels
File size: 0.26 MB

============================================================
PROCESSING 32/420
Food: Veg Spring Roll
============================================================

Searching image for: Veg Spring Roll...
Trying image 1...
Blur score (higher is sharper): 467.23
[ACCEPTED] Image 1 passed quality check.
Original size: (626, 351)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Spring Roll.jpg
Final size: 1800 × 1200 pixels
File size: 0.21 MB

============================================================
PROCESSING 33/420
Food: Paneer Tikka Biryani
============================================================

Searching image for: Paneer Tikka Biryani...
Trying image 1...
Blur score (higher is sharper): 613.58
[ACCEPTED] Image 1 passed quality check.
Original size: (467, 471)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Tikka Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.35 MB

============================================================
PROCESSING 34/420
Food: Chicken Lollipop Gravy Butter Kulcha
============================================================

Searching image for: Chicken Lollipop Gravy Butter Kulcha...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 668.02
[ACCEPTED] Image 2 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Lollipop Gravy Butter Kulcha.jpg
Final size: 1800 × 1200 pixels
File size: 0.35 MB

============================================================
PROCESSING 35/420
Food: Mushroom Dum Biryani
============================================================

Searching image for: Mushroom Dum Biryani...
Trying image 1...
Blur score (higher is sharper): 1290.08
[ACCEPTED] Image 1 passed quality check.
Original size: (800, 840)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mushroom Dum Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.47 MB

============================================================
PROCESSING 36/420
Food: Chicken Ghee Roast
============================================================

Searching image for: Chicken Ghee Roast...
Trying image 1...
Blur score (higher is sharper): 150.66
[ACCEPTED] Image 1 passed quality check.
Original size: (1202, 1596)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Ghee Roast.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB

============================================================
PROCESSING 37/420
Food: Chicken Tikka Masala Veg Manchurian Soup
============================================================

Searching image for: Chicken Tikka Masala Veg Manchurian Soup...
Trying image 1...
Blur score (higher is sharper): 907.04
[ACCEPTED] Image 1 passed quality check.
Original size: (1100, 1649)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Tikka Masala Veg Manchurian Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.56 MB

============================================================
PROCESSING 38/420
Food: Paneer Malai Tikka
============================================================

Searching image for: Paneer Malai Tikka...
Trying image 1...
Blur score (higher is sharper): 6774.04
[ACCEPTED] Image 1 passed quality check.
Original size: (713, 800)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Malai Tikka.jpg
Final size: 1800 × 1200 pixels
File size: 0.56 MB

============================================================
PROCESSING 39/420
Food: Chana Garlic Fry
============================================================

Searching image for: Chana Garlic Fry...
Trying image 1...
[SKIPPED] Image 1: HTTP 403
Trying image 2...
Blur score (higher is sharper): 2137.46
[ACCEPTED] Image 2 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chana Garlic Fry.jpg
Final size: 1800 × 1200 pixels
File size: 0.64 MB

============================================================
PROCESSING 40/420
Food: Paneer Kadai Basil Paneer Tikka
============================================================

Searching image for: Paneer Kadai Basil Paneer Tikka...
Trying image 1...
Blur score (higher is sharper): 711.79
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Kadai Basil Paneer Tikka.jpg

KeyboardInterrupt:

In [38]:
excel_file = r"C:\Users\Bharg\Downloads\Assignment - Ai agent  - Sheet1.xlsx"

report_df = run_full_pipeline(
    excel_file,
    max_items=250
)

Total food items in Excel: 420

[1] SKIPPED - Already processed:
Chicken Tandoori

[2] SKIPPED - Already processed:
Veg Fried Rice

[3] SKIPPED - Already processed:
Chicken Biryani Boneless

[4] SKIPPED - Already processed:
Butter Roti

[5] SKIPPED - Already processed:
Paneer Tikka Masala

[6] SKIPPED - Already processed:
Chicken Fried Rice

[7] SKIPPED - Already processed:
Veg Triple Schezwan Fried Rice

[8] SKIPPED - Already processed:
Roti

[9] SKIPPED - Already processed:
Chicken Tandoori

[10] SKIPPED - Already processed:
Dal Khichdi Tadka Chicken Triple Fried Rice

[11] SKIPPED - Already processed:
Chicken Lollipop

[12] SKIPPED - Already processed:
Naan

[13] SKIPPED - Already processed:
Chicken Chilli Chicken Kala Masala

[14] SKIPPED - Already processed:
Dal Tadka

[15] SKIPPED - Already processed:
Paneer Crispy

[16] SKIPPED - Already processed:
Butter Naan Chicken Crispy

[17] SKIPPED - Already processed:
Chicken Masala Boneless

[18] SKIPPED - Already processed:
Chicken Tandoori

[19] SKIPPED - Already processed:
Veg Handi

[20] SKIPPED - Already processed:
Veg Dum Biryani

[21] SKIPPED - Already processed:
Chicken Tikka Biryani

[22] SKIPPED - Already processed:
Veg Manchurian

[23] SKIPPED - Already processed:
Kulcha

[24] SKIPPED - Already processed:
Veg Kolhapuri

[25] SKIPPED - Already processed:
Chicken Schezwan Fried Rice

[26] SKIPPED - Already processed:
Paneer Kolhapuri

[27] SKIPPED - Already processed:
Paneer Makhanwala

[28] SKIPPED - Already processed:
Chicken KL Special Soup

[29] SKIPPED - Already processed:
Chicken Lollipop Tandoori

[30] SKIPPED - Already processed:
Jeera Rice

[31] SKIPPED - Already processed:
Veg Manchow Soup Veg Crispy

[32] SKIPPED - Already processed:
Veg Spring Roll

[33] SKIPPED - Already processed:
Paneer Tikka Biryani

[34] SKIPPED - Already processed:
Chicken Lollipop Gravy Butter Kulcha

[35] SKIPPED - Already processed:
Mushroom Dum Biryani

[36] SKIPPED - Already processed:
Chicken Ghee Roast

[37] SKIPPED - Already processed:
Chicken Tikka Masala Veg Manchurian Soup

[38] SKIPPED - Already processed:
Paneer Malai Tikka

[39] SKIPPED - Already processed:
Chana Garlic Fry

[40] SKIPPED - Already processed:
Paneer Kadai Basil Paneer Tikka

[41] SKIPPED - Already processed:
Chicken Hakka Noodles

[42] SKIPPED - Already processed:
Chicken KL Special Biryani

[43] SKIPPED - Already processed:
Mushroom Handi Kadai Paneer 65

[44] SKIPPED - Already processed:
Corn Cheese Balls

[45] SKIPPED - Already processed:
Paratha

[46] SKIPPED - Already processed:
Veg Burnt Chilli Garlic Fried Rice Butter Paratha

[47] SKIPPED - Already processed:
Paneer Hyderabadi Biryani

[48] SKIPPED - Already processed:
Veg KL Special Biryani

[49] SKIPPED - Already processed:
Veg Hong Kong Fried Rice Chicken Hot Garlic

[50] SKIPPED - Already processed:
Veg Hyderabadi Biryani

[51] SKIPPED - Already processed:
Veg Kadai

[52] SKIPPED - Already processed:
Mutton Rogan Josh

[53] SKIPPED - Already processed:
Veg Schezwan Fried Rice

[54] SKIPPED - Already processed:
Veg Lollipop

[55] SKIPPED - Already processed:
Dal Palak Khichdi Paneer Matar

[56] SKIPPED - Already processed:
Chicken Tawa Masala

[57] SKIPPED - Already processed:
Chicken Lollipop Masala Gravy

[58] SKIPPED - Already processed:
Chicken Green Masala Veg Manchurian Fried Rice

[59] SKIPPED - Already processed:
Veg Hakka Noodles

[60] SKIPPED - Already processed:
Chicken Pahadi Kebab

[61] SKIPPED - Already processed:
Fingers Chips Veg Diwani Handi

[62] SKIPPED - Already processed:
Chicken Manchow Soup

[63] SKIPPED - Already processed:
Mushroom Tikka Biryani

[64] SKIPPED - Already processed:
Chicken Manchurian Fried Rice Chicken Dum Biryani

[65] SKIPPED - Already processed:
Chicken Do Pyaaza

[66] SKIPPED - Already processed:
Chicken Chopper Fried Rice

[67] SKIPPED - Already processed:
Chicken Kadai Mushroom Chilli

[68] SKIPPED - Already processed:
Chicken Liver Oil Fry

[69] SKIPPED - Already processed:
Mutton Clear Soup

[70] SKIPPED - Already processed:
Paneer Handi Chicken Masala

[71] SKIPPED - Already processed:
Dal Khichdi

[72] SKIPPED - Already processed:
Chicken Banjara Kebab

[73] SKIPPED - Already processed:
Veg Pulao

[74] SKIPPED - Already processed:
Butter Garlic Naan

[75] SKIPPED - Already processed:
Chicken Kalimiri Tandoori

[76] SKIPPED - Already processed:
Chicken Fried Rice

[77] SKIPPED - Already processed:
Butter Roti

[78] SKIPPED - Already processed:
Chicken Tandoori

[79] SKIPPED - Already processed:
Chicken Lollipop

[80] SKIPPED - Already processed:
Veg Fried Rice Dal Khichdi Tadka

[81] SKIPPED - Already processed:
Veg Dum Biryani

[82] SKIPPED - Already processed:
Chicken Triple Fried Rice

[83] SKIPPED - Already processed:
Chicken Manchow Soup Chicken Biryani Boneless

[84] SKIPPED - Already processed:
Roti

[85] SKIPPED - Already processed:
Veg Manchow Soup

[86] SKIPPED - Already processed:
Butter Naan

[87] SKIPPED - Already processed:
Paneer Tikka Masala

[88] SKIPPED - Already processed:
Chicken Kala Masala

[89] SKIPPED - Already processed:
Chicken Crispy

[90] SKIPPED - Already processed:
Veg Kolhapuri Chicken Chilli

[91] SKIPPED - Already processed:
Chicken Tandoori

[92] SKIPPED - Already processed:
Veg Crispy

[93] SKIPPED - Already processed:
Dal Khichdi

[94] SKIPPED - Already processed:
Chicken Tikka Biryani

[95] SKIPPED - Already processed:
Paneer Crispy

[96] SKIPPED - Already processed:
Veg Schezwan Fried Rice

[97] SKIPPED - Already processed:
Veg Biryani

[98] SKIPPED - Already processed:
Chicken Tikka Masala

[99] SKIPPED - Already processed:
Chicken Dum Biryani

[100] SKIPPED - Already processed:
Chicken Masala Boneless

[101] SKIPPED - Already processed:
Paneer ChillI

[102] SKIPPED - Already processed:
Veg Hakka Noodles

[103] SKIPPED - Already processed:
Dal Fry

[104] SKIPPED - Already processed:
Chicken KL Special Biryani

[105] SKIPPED - Already processed:
Chicken Lollipop Masala Dry

[106] SKIPPED - Already processed:
Chicken Banjara Kebab

[107] SKIPPED - Already processed:
Veg Triple Schezwan Fried Rice

[108] SKIPPED - Already processed:
Veg Hyderabadi Biryani Chicken Pahadi Kebab

[109] SKIPPED - Already processed:
Egg Chilli

[110] SKIPPED - Already processed:
Chicken Schezwan Fried Rice

[111] SKIPPED - Already processed:
Mushroom Masala Chicken Kolhapuri

[112] SKIPPED - Already processed:
Paneer Kolhapuri

[113] SKIPPED - Already processed:
Paneer Kadai

[114] SKIPPED - Already processed:
Chicken Chopper Fried Rice Chicken Biryani

[115] SKIPPED - Already processed:
Dal Palak Khichdi

[116] SKIPPED - Already processed:
Paneer Palak

[117] SKIPPED - Already processed:
Chana Masala Corn Cheese Balls

[118] SKIPPED - Already processed:
Mutton Clear Soup

[119] SKIPPED - Already processed:
Chicken Hakka Noodles

[120] SKIPPED - Already processed:
Paneer Handi Mushroom Chilli

[121] SKIPPED - Already processed:
Egg Triple Fried Rice

[122] SKIPPED - Already processed:
Chicken Butter Garlic

[123] SKIPPED - Already processed:
Egg Half Fry Chicken Garlic

[124] SKIPPED - Already processed:
Veg Singapuri Noodles

[125] SKIPPED - Already processed:
Steamed Rice

[126] SKIPPED - Already processed:
Egg Bhurji

[127] SKIPPED - Already processed:
Veg Combination Fried Rice

[128] SKIPPED - Already processed:
Paneer Matar

[129] SKIPPED - Already processed:
Mushroom Handi Kadai

[130] SKIPPED - Already processed:
Kaju Masala

[131] SKIPPED - Already processed:
Chicken Seekh Kebab

[132] SKIPPED - Already processed:
Veg KL Special Soup

[133] SKIPPED - Already processed:
Chicken Hot Garlic Paneer Pahadi Kebab

[134] SKIPPED - Already processed:
Egg Fried Rice

[135] SKIPPED - Already processed:
Chicken Manchurian Fried Rice

[136] SKIPPED - Already processed:
Paneer Tikka Biryani Paneer Hyderabadi Biryani

[137] SKIPPED - Already processed:
Veg Burnt Chilli Garlic Fried Rice

[138] SKIPPED - Already processed:
Veg Handi

[139] SKIPPED - Already processed:
Naan

[140] SKIPPED - Already processed:
Hot and Sour Chicken Soup

[141] SKIPPED - Already processed:
Veg KL Special Biryani

[142] SKIPPED - Already processed:
Chicken Koliwada

[143] SKIPPED - Already processed:
Chicken Handi Veg Pulao

[144] SKIPPED - Already processed:
Chicken Hong Kong Noodles

[145] SKIPPED - Already processed:
Chicken Lollipop Tandoori

[146] SKIPPED - Already processed:
Egg Noodles Egg 65

[147] SKIPPED - Already processed:
Mushroom Tikka Biryani

[148] SKIPPED - Already processed:
Chicken Manchurian Soup

[149] SKIPPED - Already processed:
Veg Pot Fried Rice Sweet Corn Veg Soup

[150] SKIPPED - Already processed:
Chicken Hyderabadi Biryani

[151] SKIPPED - Already processed:
Veg Lahori Masala

[152] SKIPPED - Already processed:
Chicken Schezwan Noodles Chicken Lollipop Masala Gravy

============================================================
PROCESSING 153/420
Food: Mutton Pepper Soup
============================================================

Searching image for: Mutton Pepper Soup...
Trying image 1...
Blur score (higher is sharper): 37.10
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 63.31
[REJECTED] Image 2 is too blurry.
Trying image 3...
[SKIPPED] Image 3 failed: HTTPSConnectionPool(host='www.coastalcurryandgrill.com', port=443): Max retries exceeded with url: /images/mutton-soup-recipe-in-hindi.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022205C05BD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[FAILED] No suitable image found for Mutton Pepper Soup

[154] SKIPPED - Already processed:
Chicken Popcorn

[155] SKIPPED - Already processed:
Chicken Kung Pao

[156] SKIPPED - Already processed:
Curd Rice

[157] SKIPPED - Already processed:
Chicken Liver Masala Fry

[158] SKIPPED - Already processed:
Mutton Masala Mutton Kadai

[159] SKIPPED - Already processed:
Egg Omelette

[160] SKIPPED - Already processed:
Veg Schezwan Noodles

[161] SKIPPED - Already processed:
Chicken Pot Fried Rice Paneer Manchurian

[162] SKIPPED - Already processed:
Chicken KL Special Fried Rice

[163] SKIPPED - Already processed:
Chicken Peshawari

[164] SKIPPED - Already processed:
Mutton Kala Masala Dal Palak

[165] SKIPPED - Already processed:
Veg Manchurian Noodles

[166] SKIPPED - Already processed:
Chicken Angara Kebab

[167] SKIPPED - Already processed:
Chicken Oily Fry Fingers Chips

[168] SKIPPED - Already processed:
Chicken Dragon

[169] SKIPPED - Already processed:
Dal Tadka

[170] SKIPPED - Already processed:
Paneer Makhanwala

============================================================
PROCESSING 171/420
Food: Chicken Hong Kong Fried Rice
============================================================

Searching image for: Chicken Hong Kong Fried Rice...
Trying image 1...
[SKIPPED] Image 1 failed: HTTPSConnectionPool(host='hungryforever.net', port=443): Read timed out. (read timeout=7)
Trying image 2...
[SKIPPED] Image 2: not a valid image
Trying image 3...
[SKIPPED] Image 3: not a valid image
[FAILED] No suitable image found for Chicken Hong Kong Fried Rice

[172] SKIPPED - Already processed:
Mutton Rogan Josh

[173] SKIPPED - Already processed:
Chicken Lollipop Gravy

[174] SKIPPED - Already processed:
Veg Manchurian Gravy Mutton Lucknow Biryani

[175] SKIPPED - Already processed:
Chicken Chilli Gravy

[176] SKIPPED - Already processed:
Kulcha

[177] SKIPPED - Already processed:
Paneer Lehsuni Kebab Paneer Malai Tikka

[178] SKIPPED - Already processed:
Jeera Rice

[179] SKIPPED - Already processed:
Paratha

[180] SKIPPED - Already processed:
Veg Spring Roll

[181] SKIPPED - Already processed:
Chicken Kalimiri Tandoori

[182] SKIPPED - Already processed:
Chicken Singapuri Fried Rice

[183] SKIPPED - Already processed:
Cream of Tomato Soup Chicken Kadai

[184] SKIPPED - Already processed:
Veg Patiala

[185] SKIPPED - Already processed:
KL Special Mutton Biryani

[186] SKIPPED - Already processed:
Veg Manchurian Soup Veg Kadai

[187] SKIPPED - Already processed:
Classic Paneer Tikka

[188] SKIPPED - Already processed:
Chicken Hyderabadi

[189] SKIPPED - Already processed:
Chicken Junglee Fry Chicken Tiranga Kebab

[190] SKIPPED - Already processed:
Chana Garlic Fry

[191] SKIPPED - Already processed:
Veg Chowmein

[192] SKIPPED - Already processed:
Chicken Lollipop Chicken Tandoori

[193] SKIPPED - Already processed:
Chicken Crispy

[194] SKIPPED - Already processed:
Chicken Chilli

[195] SKIPPED - Already processed:
Dal Khichdi Tadka Chicken Manchow Soup

[196] SKIPPED - Already processed:
Butter Roti

[197] SKIPPED - Already processed:
Chicken Biryani Boneless

[198] SKIPPED - Already processed:
Chicken Hakka Noodles Chicken Fried Rice

[199] SKIPPED - Already processed:
Roti

[200] SKIPPED - Already processed:
Chicken Lollipop Masala Dry

[201] SKIPPED - Already processed:
Butter Naan

[202] SKIPPED - Already processed:
Chicken Schezwan Fried Rice

[203] SKIPPED - Already processed:
Chicken Kala Masala

[204] SKIPPED - Already processed:
Chicken Triple Fried Rice

[205] SKIPPED - Already processed:
Chicken Tikka Biryani

[206] SKIPPED - Already processed:
Veg Manchow Soup

[207] SKIPPED - Already processed:
Chicken Tikka Masala

[208] SKIPPED - Already processed:
Paneer Tikka Masala Paneer ChillI

[209] SKIPPED - Already processed:
Chicken Tandoori

[210] SKIPPED - Already processed:
Jeera Rice

[211] SKIPPED - Already processed:
Chicken Seekh Kebab Chicken Liver Masala Fry

[212] SKIPPED - Already processed:
Veg KL Special Soup

[213] SKIPPED - Already processed:
Chicken Biryani

[214] SKIPPED - Already processed:
Veg Crispy Egg Fried Rice

[215] SKIPPED - Already processed:
Veg Dum Biryani

[216] SKIPPED - Already processed:
Chicken Tikka

============================================================
PROCESSING 217/420
Food: Chicken Schezwan Noodles Chicken Pahadi Kebab
============================================================

Searching image for: Chicken Schezwan Noodles Chicken Pahadi Kebab...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 1569.80
[ACCEPTED] Image 2 passed quality check.
Original size: (1200, 900)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Schezwan Noodles Chicken Pahadi Kebab.jpg
Final size: 1800 × 1200 pixels
File size: 0.60 MB

[218] SKIPPED - Already processed:
Chicken Dum Biryani

[219] SKIPPED - Already processed:
Dal Tadka

[220] SKIPPED - Already processed:
Paneer Tikka Biryani Chicken Kalimiri Tandoori

[221] SKIPPED - Already processed:
Chicken Lollipop Tandoori

[222] SKIPPED - Already processed:
Chicken Garlic

[223] SKIPPED - Already processed:
Chicken Masala Boneless

[224] SKIPPED - Already processed:
Veg Burnt Chilli Garlic Fried Rice

[225] SKIPPED - Already processed:
Dal Khichdi

[226] SKIPPED - Already processed:
Lucknow Chicken Biryani

[227] SKIPPED - Already processed:
Butter Kulcha Chicken Patiala

[228] SKIPPED - Already processed:
Cream of Tomato Soup

[229] SKIPPED - Already processed:
Veg Triple Schezwan Fried Rice

[230] SKIPPED - Already processed:
Chicken Banjara Kebab

[231] SKIPPED - Already processed:
Corn Cheese Balls

[232] SKIPPED - Already processed:
Veg Schezwan Fried Rice

[233] SKIPPED - Already processed:
Veg Hyderabadi Biryani Mushroom Chilli

[234] SKIPPED - Already processed:
Chicken Pot Fried Rice

[235] SKIPPED - Already processed:
Egg Schezwan Fried Rice

[236] SKIPPED - Already processed:
Egg 65

[237] SKIPPED - Already processed:
Veg Kolhapuri

[238] SKIPPED - Already processed:
Hot and Sour Chicken Soup

[239] SKIPPED - Already processed:
Paneer Crispy

[240] SKIPPED - Already processed:
Chicken Keema Masala Paneer Pahadi Kebab

[241] SKIPPED - Already processed:
Kaju Masala

[242] SKIPPED - Already processed:
Veg Handi

[243] SKIPPED - Already processed:
Chicken Afghani Mutton Clear Soup

[244] SKIPPED - Already processed:
Chicken Popcorn

[245] SKIPPED - Already processed:
Chicken Tandoor Masala

[246] SKIPPED - Already processed:
Mushroom Handi Kadai Paneer Masala

[247] SKIPPED - Already processed:
Cheesy Spaghetti

[248] SKIPPED - Already processed:
Veg Manchurian

[249] SKIPPED - Already processed:
Veg Fried Rice

[250] SKIPPED - Already processed:
Chicken Manchurian Soup

[251] SKIPPED - Already processed:
Mutton Masala

[252] SKIPPED - Already processed:
Paneer Chilli Gravy

[253] SKIPPED - Already processed:
Naan

[254] SKIPPED - Already processed:
Chicken Liver Oil Fry

============================================================
PROCESSING 255/420
Food: Mushroom Butter Fry
============================================================

Searching image for: Mushroom Butter Fry...
Trying image 1...
Blur score (higher is sharper): 147.70
[ACCEPTED] Image 1 passed quality check.
Original size: (1200, 1518)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mushroom Butter Fry.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB

Reached processing limit.

IndexError: At least one sheet must be visible

In [42]:
excel_file = r"C:\Users\Bharg\Downloads\Assignment - Ai agent  - Sheet1.xlsx"

run_full_pipeline(
    excel_file,
    target_images=250
)

Already processed: 179
Target: 250
Remaining: 71

[1] SKIPPED:
Chicken Tandoori

[2] SKIPPED:
Veg Fried Rice

[3] SKIPPED:
Chicken Biryani Boneless

[4] SKIPPED:
Butter Roti

[5] SKIPPED:
Paneer Tikka Masala

[6] SKIPPED:
Chicken Fried Rice

[7] SKIPPED:
Veg Triple Schezwan Fried Rice

[8] SKIPPED:
Roti

[9] SKIPPED:
Chicken Tandoori

[10] SKIPPED:
Dal Khichdi Tadka Chicken Triple Fried Rice

[11] SKIPPED:
Chicken Lollipop

[12] SKIPPED:
Naan

[13] SKIPPED:
Chicken Chilli Chicken Kala Masala

[14] SKIPPED:
Dal Tadka

[15] SKIPPED:
Paneer Crispy

[16] SKIPPED:
Butter Naan Chicken Crispy

[17] SKIPPED:
Chicken Masala Boneless

[18] SKIPPED:
Chicken Tandoori

[19] SKIPPED:
Veg Handi

[20] SKIPPED:
Veg Dum Biryani

[21] SKIPPED:
Chicken Tikka Biryani

[22] SKIPPED:
Veg Manchurian

[23] SKIPPED:
Kulcha

[24] SKIPPED:
Veg Kolhapuri

[25] SKIPPED:
Chicken Schezwan Fried Rice

[26] SKIPPED:
Paneer Kolhapuri

[27] SKIPPED:
Paneer Makhanwala

[28] SKIPPED:
Chicken KL Special Soup

[29] SKIPPED:
Chicken Lollipop Tandoori

[30] SKIPPED:
Jeera Rice

[31] SKIPPED:
Veg Manchow Soup Veg Crispy

[32] SKIPPED:
Veg Spring Roll

[33] SKIPPED:
Paneer Tikka Biryani

[34] SKIPPED:
Chicken Lollipop Gravy Butter Kulcha

[35] SKIPPED:
Mushroom Dum Biryani

[36] SKIPPED:
Chicken Ghee Roast

[37] SKIPPED:
Chicken Tikka Masala Veg Manchurian Soup

[38] SKIPPED:
Paneer Malai Tikka

[39] SKIPPED:
Chana Garlic Fry

[40] SKIPPED:
Paneer Kadai Basil Paneer Tikka

[41] SKIPPED:
Chicken Hakka Noodles

[42] SKIPPED:
Chicken KL Special Biryani

[43] SKIPPED:
Mushroom Handi Kadai Paneer 65

[44] SKIPPED:
Corn Cheese Balls

[45] SKIPPED:
Paratha

[46] SKIPPED:
Veg Burnt Chilli Garlic Fried Rice Butter Paratha

[47] SKIPPED:
Paneer Hyderabadi Biryani

[48] SKIPPED:
Veg KL Special Biryani

[49] SKIPPED:
Veg Hong Kong Fried Rice Chicken Hot Garlic

[50] SKIPPED:
Veg Hyderabadi Biryani

[51] SKIPPED:
Veg Kadai

[52] SKIPPED:
Mutton Rogan Josh

[53] SKIPPED:
Veg Schezwan Fried Rice

[54] SKIPPED:
Veg Lollipop

[55] SKIPPED:
Dal Palak Khichdi Paneer Matar

[56] SKIPPED:
Chicken Tawa Masala

[57] SKIPPED:
Chicken Lollipop Masala Gravy

[58] SKIPPED:
Chicken Green Masala Veg Manchurian Fried Rice

[59] SKIPPED:
Veg Hakka Noodles

[60] SKIPPED:
Chicken Pahadi Kebab

[61] SKIPPED:
Fingers Chips Veg Diwani Handi

[62] SKIPPED:
Chicken Manchow Soup

[63] SKIPPED:
Mushroom Tikka Biryani

[64] SKIPPED:
Chicken Manchurian Fried Rice Chicken Dum Biryani

[65] SKIPPED:
Chicken Do Pyaaza

[66] SKIPPED:
Chicken Chopper Fried Rice

[67] SKIPPED:
Chicken Kadai Mushroom Chilli

[68] SKIPPED:
Chicken Liver Oil Fry

[69] SKIPPED:
Mutton Clear Soup

[70] SKIPPED:
Paneer Handi Chicken Masala

[71] SKIPPED:
Dal Khichdi

[72] SKIPPED:
Chicken Banjara Kebab

[73] SKIPPED:
Veg Pulao

[74] SKIPPED:
Butter Garlic Naan

[75] SKIPPED:
Chicken Kalimiri Tandoori

[76] SKIPPED:
Chicken Fried Rice

[77] SKIPPED:
Butter Roti

[78] SKIPPED:
Chicken Tandoori

[79] SKIPPED:
Chicken Lollipop

[80] SKIPPED:
Veg Fried Rice Dal Khichdi Tadka

[81] SKIPPED:
Veg Dum Biryani

[82] SKIPPED:
Chicken Triple Fried Rice

[83] SKIPPED:
Chicken Manchow Soup Chicken Biryani Boneless

[84] SKIPPED:
Roti

[85] SKIPPED:
Veg Manchow Soup

[86] SKIPPED:
Butter Naan

[87] SKIPPED:
Paneer Tikka Masala

[88] SKIPPED:
Chicken Kala Masala

[89] SKIPPED:
Chicken Crispy

[90] SKIPPED:
Veg Kolhapuri Chicken Chilli

[91] SKIPPED:
Chicken Tandoori

[92] SKIPPED:
Veg Crispy

[93] SKIPPED:
Dal Khichdi

[94] SKIPPED:
Chicken Tikka Biryani

[95] SKIPPED:
Paneer Crispy

[96] SKIPPED:
Veg Schezwan Fried Rice

[97] SKIPPED:
Veg Biryani

[98] SKIPPED:
Chicken Tikka Masala

[99] SKIPPED:
Chicken Dum Biryani

[100] SKIPPED:
Chicken Masala Boneless

[101] SKIPPED:
Paneer ChillI

[102] SKIPPED:
Veg Hakka Noodles

[103] SKIPPED:
Dal Fry

[104] SKIPPED:
Chicken KL Special Biryani

[105] SKIPPED:
Chicken Lollipop Masala Dry

[106] SKIPPED:
Chicken Banjara Kebab

[107] SKIPPED:
Veg Triple Schezwan Fried Rice

[108] SKIPPED:
Veg Hyderabadi Biryani Chicken Pahadi Kebab

[109] SKIPPED:
Egg Chilli

[110] SKIPPED:
Chicken Schezwan Fried Rice

[111] SKIPPED:
Mushroom Masala Chicken Kolhapuri

[112] SKIPPED:
Paneer Kolhapuri

[113] SKIPPED:
Paneer Kadai

[114] SKIPPED:
Chicken Chopper Fried Rice Chicken Biryani

[115] SKIPPED:
Dal Palak Khichdi

[116] SKIPPED:
Paneer Palak

[117] SKIPPED:
Chana Masala Corn Cheese Balls

[118] SKIPPED:
Mutton Clear Soup

[119] SKIPPED:
Chicken Hakka Noodles

[120] SKIPPED:
Paneer Handi Mushroom Chilli

[121] SKIPPED:
Egg Triple Fried Rice

[122] SKIPPED:
Chicken Butter Garlic

[123] SKIPPED:
Egg Half Fry Chicken Garlic

[124] SKIPPED:
Veg Singapuri Noodles

[125] SKIPPED:
Steamed Rice

[126] SKIPPED:
Egg Bhurji

[127] SKIPPED:
Veg Combination Fried Rice

[128] SKIPPED:
Paneer Matar

[129] SKIPPED:
Mushroom Handi Kadai

[130] SKIPPED:
Kaju Masala

[131] SKIPPED:
Chicken Seekh Kebab

[132] SKIPPED:
Veg KL Special Soup

[133] SKIPPED:
Chicken Hot Garlic Paneer Pahadi Kebab

[134] SKIPPED:
Egg Fried Rice

[135] SKIPPED:
Chicken Manchurian Fried Rice

[136] SKIPPED:
Paneer Tikka Biryani Paneer Hyderabadi Biryani

[137] SKIPPED:
Veg Burnt Chilli Garlic Fried Rice

[138] SKIPPED:
Veg Handi

[139] SKIPPED:
Naan

[140] SKIPPED:
Hot and Sour Chicken Soup

[141] SKIPPED:
Veg KL Special Biryani

[142] SKIPPED:
Chicken Koliwada

[143] SKIPPED:
Chicken Handi Veg Pulao

[144] SKIPPED:
Chicken Hong Kong Noodles

[145] SKIPPED:
Chicken Lollipop Tandoori

[146] SKIPPED:
Egg Noodles Egg 65

[147] SKIPPED:
Mushroom Tikka Biryani

[148] SKIPPED:
Chicken Manchurian Soup

[149] SKIPPED:
Veg Pot Fried Rice Sweet Corn Veg Soup

[150] SKIPPED:
Chicken Hyderabadi Biryani

[151] SKIPPED:
Veg Lahori Masala

[152] SKIPPED:
Chicken Schezwan Noodles Chicken Lollipop Masala Gravy

============================================================
PROCESSING
Food: Mutton Pepper Soup
Progress: 179/250
============================================================

Searching image for: Mutton Pepper Soup...
Trying image 1...
Blur score (higher is sharper): 37.10
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 63.31
[REJECTED] Image 2 is too blurry.
Trying image 3...
[SKIPPED] Image 3 failed: HTTPSConnectionPool(host='www.coastalcurryandgrill.com', port=443): Max retries exceeded with url: /images/mutton-soup-recipe-in-hindi.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022202E2A5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[FAILED] No suitable image found for Mutton Pepper Soup

[154] SKIPPED:
Chicken Popcorn

[155] SKIPPED:
Chicken Kung Pao

[156] SKIPPED:
Curd Rice

[157] SKIPPED:
Chicken Liver Masala Fry

[158] SKIPPED:
Mutton Masala Mutton Kadai

[159] SKIPPED:
Egg Omelette

[160] SKIPPED:
Veg Schezwan Noodles

[161] SKIPPED:
Chicken Pot Fried Rice Paneer Manchurian

[162] SKIPPED:
Chicken KL Special Fried Rice

[163] SKIPPED:
Chicken Peshawari

[164] SKIPPED:
Mutton Kala Masala Dal Palak

[165] SKIPPED:
Veg Manchurian Noodles

[166] SKIPPED:
Chicken Angara Kebab

[167] SKIPPED:
Chicken Oily Fry Fingers Chips

[168] SKIPPED:
Chicken Dragon

[169] SKIPPED:
Dal Tadka

[170] SKIPPED:
Paneer Makhanwala

============================================================
PROCESSING
Food: Chicken Hong Kong Fried Rice
Progress: 179/250
============================================================

Searching image for: Chicken Hong Kong Fried Rice...
Trying image 1...
[SKIPPED] Image 1 failed: HTTPSConnectionPool(host='hungryforever.net', port=443): Read timed out. (read timeout=7)
Trying image 2...
[SKIPPED] Image 2: not a valid image
Trying image 3...
[SKIPPED] Image 3: not a valid image
[FAILED] No suitable image found for Chicken Hong Kong Fried Rice

[172] SKIPPED:
Mutton Rogan Josh

[173] SKIPPED:
Chicken Lollipop Gravy

[174] SKIPPED:
Veg Manchurian Gravy Mutton Lucknow Biryani

[175] SKIPPED:
Chicken Chilli Gravy

[176] SKIPPED:
Kulcha

[177] SKIPPED:
Paneer Lehsuni Kebab Paneer Malai Tikka

[178] SKIPPED:
Jeera Rice

[179] SKIPPED:
Paratha

[180] SKIPPED:
Veg Spring Roll

[181] SKIPPED:
Chicken Kalimiri Tandoori

[182] SKIPPED:
Chicken Singapuri Fried Rice

[183] SKIPPED:
Cream of Tomato Soup Chicken Kadai

[184] SKIPPED:
Veg Patiala

[185] SKIPPED:
KL Special Mutton Biryani

[186] SKIPPED:
Veg Manchurian Soup Veg Kadai

[187] SKIPPED:
Classic Paneer Tikka

[188] SKIPPED:
Chicken Hyderabadi

[189] SKIPPED:
Chicken Junglee Fry Chicken Tiranga Kebab

[190] SKIPPED:
Chana Garlic Fry

[191] SKIPPED:
Veg Chowmein

[192] SKIPPED:
Chicken Lollipop Chicken Tandoori

[193] SKIPPED:
Chicken Crispy

[194] SKIPPED:
Chicken Chilli

[195] SKIPPED:
Dal Khichdi Tadka Chicken Manchow Soup

[196] SKIPPED:
Butter Roti

[197] SKIPPED:
Chicken Biryani Boneless

[198] SKIPPED:
Chicken Hakka Noodles Chicken Fried Rice

[199] SKIPPED:
Roti

[200] SKIPPED:
Chicken Lollipop Masala Dry

[201] SKIPPED:
Butter Naan

[202] SKIPPED:
Chicken Schezwan Fried Rice

[203] SKIPPED:
Chicken Kala Masala

[204] SKIPPED:
Chicken Triple Fried Rice

[205] SKIPPED:
Chicken Tikka Biryani

[206] SKIPPED:
Veg Manchow Soup

[207] SKIPPED:
Chicken Tikka Masala

[208] SKIPPED:
Paneer Tikka Masala Paneer ChillI

[209] SKIPPED:
Chicken Tandoori

[210] SKIPPED:
Jeera Rice

[211] SKIPPED:
Chicken Seekh Kebab Chicken Liver Masala Fry

[212] SKIPPED:
Veg KL Special Soup

[213] SKIPPED:
Chicken Biryani

[214] SKIPPED:
Veg Crispy Egg Fried Rice

[215] SKIPPED:
Veg Dum Biryani

[216] SKIPPED:
Chicken Tikka

[217] SKIPPED:
Chicken Schezwan Noodles Chicken Pahadi Kebab

[218] SKIPPED:
Chicken Dum Biryani

[219] SKIPPED:
Dal Tadka

[220] SKIPPED:
Paneer Tikka Biryani Chicken Kalimiri Tandoori

[221] SKIPPED:
Chicken Lollipop Tandoori

[222] SKIPPED:
Chicken Garlic

[223] SKIPPED:
Chicken Masala Boneless

[224] SKIPPED:
Veg Burnt Chilli Garlic Fried Rice

[225] SKIPPED:
Dal Khichdi

[226] SKIPPED:
Lucknow Chicken Biryani

[227] SKIPPED:
Butter Kulcha Chicken Patiala

[228] SKIPPED:
Cream of Tomato Soup

[229] SKIPPED:
Veg Triple Schezwan Fried Rice

[230] SKIPPED:
Chicken Banjara Kebab

[231] SKIPPED:
Corn Cheese Balls

[232] SKIPPED:
Veg Schezwan Fried Rice

[233] SKIPPED:
Veg Hyderabadi Biryani Mushroom Chilli

[234] SKIPPED:
Chicken Pot Fried Rice

[235] SKIPPED:
Egg Schezwan Fried Rice

[236] SKIPPED:
Egg 65

[237] SKIPPED:
Veg Kolhapuri

[238] SKIPPED:
Hot and Sour Chicken Soup

[239] SKIPPED:
Paneer Crispy

[240] SKIPPED:
Chicken Keema Masala Paneer Pahadi Kebab

[241] SKIPPED:
Kaju Masala

[242] SKIPPED:
Veg Handi

[243] SKIPPED:
Chicken Afghani Mutton Clear Soup

[244] SKIPPED:
Chicken Popcorn

[245] SKIPPED:
Chicken Tandoor Masala

[246] SKIPPED:
Mushroom Handi Kadai Paneer Masala

[247] SKIPPED:
Cheesy Spaghetti

[248] SKIPPED:
Veg Manchurian

[249] SKIPPED:
Veg Fried Rice

[250] SKIPPED:
Chicken Manchurian Soup

[251] SKIPPED:
Mutton Masala

[252] SKIPPED:
Paneer Chilli Gravy

[253] SKIPPED:
Naan

[254] SKIPPED:
Chicken Liver Oil Fry

[255] SKIPPED:
Mushroom Butter Fry

[256] SKIPPED:
Chicken Hyderabadi Biryani

[257] SKIPPED:
Chicken Hyderabadi

============================================================
PROCESSING
Food: Veg Pot Fried Rice
Progress: 179/250
============================================================

Searching image for: Veg Pot Fried Rice...
Trying image 1...
Blur score (higher is sharper): 126.79
[ACCEPTED] Image 1 passed quality check.
Original size: (1050, 700)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Pot Fried Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.27 MB
SUCCESS: 180/250

============================================================
PROCESSING
Food: Mutton Manchow Soup
Progress: 180/250
============================================================

Searching image for: Mutton Manchow Soup...
Trying image 1...
Blur score (higher is sharper): 142.51
[ACCEPTED] Image 1 passed quality check.
Original size: (600, 464)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Manchow Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.23 MB
SUCCESS: 181/250

============================================================
PROCESSING
Food: Chicken KL Special Fried Rice Classic Chicken Creamy Salad
Progress: 181/250
============================================================

Searching image for: Chicken KL Special Fried Rice Classic Chicken Creamy Salad...
Trying image 1...
Blur score (higher is sharper): 1142.93
[ACCEPTED] Image 1 passed quality check.
Original size: (1000, 1000)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken KL Special Fried Rice Classic Chicken Creamy Salad.jpg
Final size: 1800 × 1200 pixels
File size: 0.53 MB
SUCCESS: 182/250

[261] SKIPPED:
Veg KL Special Biryani

============================================================
PROCESSING
Food: Mutton Kala Masala
Progress: 182/250
============================================================

Searching image for: Mutton Kala Masala...
Trying image 1...
Blur score (higher is sharper): 553.66
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 683)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Kala Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.43 MB
SUCCESS: 183/250

[263] SKIPPED:
Veg Lollipop

[264] SKIPPED:
Chicken Butter Garlic

[265] SKIPPED:
Veg Hakka Noodles

[266] SKIPPED:
Chicken Ghee Roast

============================================================
PROCESSING
Food: Chicken Handi Chicken Lahori Masala
Progress: 183/250
============================================================

Searching image for: Chicken Handi Chicken Lahori Masala...
Trying image 1...
Blur score (higher is sharper): 2233.39
[ACCEPTED] Image 1 passed quality check.
Original size: (800, 533)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Handi Chicken Lahori Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.30 MB
SUCCESS: 184/250

[268] SKIPPED:
Veg Schezwan Noodles

============================================================
PROCESSING
Food: Chicken Kolhapuri
Progress: 184/250
============================================================

Searching image for: Chicken Kolhapuri...
Trying image 1...
Blur score (higher is sharper): 637.78
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Kolhapuri.jpg
Final size: 1800 × 1200 pixels
File size: 0.49 MB
SUCCESS: 185/250

============================================================
PROCESSING
Food: Veg Singapuri Noodles Chicken Malai Kebab
Progress: 185/250
============================================================

Searching image for: Veg Singapuri Noodles Chicken Malai Kebab...
Trying image 1...
Blur score (higher is sharper): 219.16
[ACCEPTED] Image 1 passed quality check.
Original size: (800, 800)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Singapuri Noodles Chicken Malai Kebab.jpg
Final size: 1800 × 1200 pixels
File size: 0.24 MB
SUCCESS: 186/250

[271] SKIPPED:
Chicken KL Special Soup

[272] SKIPPED:
Chicken Lollipop Masala Gravy

============================================================
PROCESSING
Food: Chicken Kung Pao Chicken KL Special Biryani
Progress: 186/250
============================================================

Searching image for: Chicken Kung Pao Chicken KL Special Biryani...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 1616.90
[ACCEPTED] Image 2 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Kung Pao Chicken KL Special Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.54 MB
SUCCESS: 187/250

============================================================
PROCESSING
Food: Chicken Hot Garlic
Progress: 187/250
============================================================

Searching image for: Chicken Hot Garlic...
Trying image 1...
Blur score (higher is sharper): 555.76
[ACCEPTED] Image 1 passed quality check.
Original size: (705, 663)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Hot Garlic.jpg
Final size: 1800 × 1200 pixels
File size: 0.43 MB
SUCCESS: 188/250

[275] SKIPPED:
Chicken Chilli Gravy

[276] SKIPPED:
Dal Fry

============================================================
PROCESSING
Food: Basil Paneer Tikka
Progress: 188/250
============================================================

Searching image for: Basil Paneer Tikka...
Trying image 1...
Blur score (higher is sharper): 87.65
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 2000)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Basil Paneer Tikka.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB
SUCCESS: 189/250

============================================================
PROCESSING
Food: Murgh Musallam
Progress: 189/250
============================================================

Searching image for: Murgh Musallam...
Trying image 1...
Blur score (higher is sharper): 90.99
[ACCEPTED] Image 1 passed quality check.
Original size: (2002, 2007)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Murgh Musallam.jpg
Final size: 1800 × 1200 pixels
File size: 0.45 MB
SUCCESS: 190/250

============================================================
PROCESSING
Food: Veg Diwani Handi
Progress: 190/250
============================================================

Searching image for: Veg Diwani Handi...
Trying image 1...
Blur score (higher is sharper): 506.72
[ACCEPTED] Image 1 passed quality check.
Original size: (768, 768)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Diwani Handi.jpg
Final size: 1800 × 1200 pixels
File size: 0.30 MB
SUCCESS: 191/250

============================================================
PROCESSING
Food: Paneer Kolhapuri Paneer Biryani
Progress: 191/250
============================================================

Searching image for: Paneer Kolhapuri Paneer Biryani...
Trying image 1...
Blur score (higher is sharper): 137.65
[ACCEPTED] Image 1 passed quality check.
Original size: (2121, 1414)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Kolhapuri Paneer Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.45 MB
SUCCESS: 192/250

============================================================
PROCESSING
Food: Mutton Lucknow Biryani
Progress: 192/250
============================================================

Searching image for: Mutton Lucknow Biryani...
Trying image 1...
Blur score (higher is sharper): 207.27
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 1333)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Lucknow Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.38 MB
SUCCESS: 193/250

[282] SKIPPED:
Chicken Chopper Fried Rice

============================================================
PROCESSING
Food: Chicken Lung Fung Soup
Progress: 193/250
============================================================

Searching image for: Chicken Lung Fung Soup...
Trying image 1...
Blur score (higher is sharper): 557.10
[ACCEPTED] Image 1 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Lung Fung Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.30 MB
SUCCESS: 194/250

============================================================
PROCESSING
Food: Mutton Soup
Progress: 194/250
============================================================

Searching image for: Mutton Soup...
Trying image 1...
Blur score (higher is sharper): 375.08
[ACCEPTED] Image 1 passed quality check.
Original size: (1300, 956)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.32 MB
SUCCESS: 195/250


C:\Users\Bharg\anaconda3\Lib\site-packages\PIL\Image.py:1136: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(

Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 483.13
[ACCEPTED] Image 2 passed quality check.
Original size: (1025, 1025)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Schezwan Fried Rice Chicken Pahadi Kebab.jpg
Final size: 1800 × 1200 pixels
File size: 0.52 MB
SUCCESS: 208/250

[331] SKIPPED:
Dal Fry

[332] SKIPPED:
Chicken Hakka Noodles

============================================================
PROCESSING
Food: Chicken KL Special Fried Rice Mushroom Chilli
Progress: 208/250
============================================================

Searching image for: Chicken KL Special Fried Rice Mushroom Chilli...
Trying image 1...
Blur score (higher is sharper): 534.68
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 1333)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken KL Special Fried Rice Mushroom Chilli.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB
SUCCESS: 209/250

[334] SKIPPED:
Dal Khichdi

============================================================
PROCESSING
Food: Chicken Lajawab
Progress: 209/250
============================================================

Searching image for: Chicken Lajawab...
Trying image 1...
Blur score (higher is sharper): 1277.29
[ACCEPTED] Image 1 passed quality check.
Original size: (736, 736)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Lajawab.jpg
Final size: 1800 × 1200 pixels
File size: 0.44 MB
SUCCESS: 210/250

[336] SKIPPED:
Chicken Koliwada

[337] SKIPPED:
Veg Singapuri Noodles

[338] SKIPPED:
Egg Fried Rice

============================================================
PROCESSING
Food: Veg Manchurian Chicken Tawa Masala
Progress: 210/250
============================================================

Searching image for: Veg Manchurian Chicken Tawa Masala...
Trying image 1...
Blur score (higher is sharper): 792.18
[ACCEPTED] Image 1 passed quality check.
Original size: (1380, 1036)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Manchurian Chicken Tawa Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.50 MB
SUCCESS: 211/250

============================================================
PROCESSING
Food: Chicken Masala Fry
Progress: 211/250
============================================================

Searching image for: Chicken Masala Fry...
Trying image 1...
Blur score (higher is sharper): 156.79
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 682)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Masala Fry.jpg
Final size: 1800 × 1200 pixels
File size: 0.26 MB
SUCCESS: 212/250

============================================================
PROCESSING
Food: Mutton Rara Masala
Progress: 212/250
============================================================

Searching image for: Mutton Rara Masala...
Trying image 1...
Blur score (higher is sharper): 246.42
[ACCEPTED] Image 1 passed quality check.
Original size: (600, 600)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Rara Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.31 MB
SUCCESS: 213/250

[342] SKIPPED:
Veg Hakka Noodles

============================================================
PROCESSING
Food: Burnt Chilli Garlic Noodles
Progress: 213/250
============================================================

Searching image for: Burnt Chilli Garlic Noodles...
Trying image 1...
Blur score (higher is sharper): 411.46
[ACCEPTED] Image 1 passed quality check.
Original size: (1080, 1350)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Burnt Chilli Garlic Noodles.jpg
Final size: 1800 × 1200 pixels
File size: 0.50 MB
SUCCESS: 214/250

[344] SKIPPED:
Veg Schezwan Noodles

============================================================
PROCESSING
Food: Paneer Handi
Progress: 214/250
============================================================

Searching image for: Paneer Handi...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 1277.50
[ACCEPTED] Image 2 passed quality check.
Original size: (1000, 778)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Handi.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB
SUCCESS: 215/250

============================================================
PROCESSING
Food: Murgh Musallam Chicken Dragon
Progress: 215/250
============================================================

Searching image for: Murgh Musallam Chicken Dragon...
Trying image 1...
Blur score (higher is sharper): 90.99
[ACCEPTED] Image 1 passed quality check.
Original size: (2002, 2007)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Murgh Musallam Chicken Dragon.jpg
Final size: 1800 × 1200 pixels
File size: 0.45 MB
SUCCESS: 216/250

[347] SKIPPED:
Veg Hyderabadi Biryani

[348] SKIPPED:
Veg Manchow Soup

============================================================
PROCESSING
Food: Veg Manchurian Fried Rice Kulcha
Progress: 216/250
============================================================

Searching image for: Veg Manchurian Fried Rice Kulcha...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 3721.24
[ACCEPTED] Image 2 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Manchurian Fried Rice Kulcha.jpg
Final size: 1800 × 1200 pixels
File size: 0.53 MB
SUCCESS: 217/250

============================================================
PROCESSING
Food: Chicken Noodles Soup
Progress: 217/250
============================================================

Searching image for: Chicken Noodles Soup...
Trying image 1...
Blur score (higher is sharper): 126.57
[ACCEPTED] Image 1 passed quality check.
Original size: (3072, 2048)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Noodles Soup.jpg
Final size: 1800 × 1200 pixels
File size: 0.37 MB
SUCCESS: 218/250

[351] SKIPPED:
Mutton Rogan Josh

[352] SKIPPED:
Paneer Crispy

============================================================
PROCESSING
Food: Mutton Biryani Boneless
Progress: 218/250
============================================================

Searching image for: Mutton Biryani Boneless...
Trying image 1...
Blur score (higher is sharper): 324.28
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 1334)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Biryani Boneless.jpg
Final size: 1800 × 1200 pixels
File size: 0.43 MB
SUCCESS: 219/250

[354] SKIPPED:
Chicken Ghee Roast

[355] SKIPPED:
Chicken Popcorn

============================================================
PROCESSING
Food: Boiled Egg Bhurji Mushroom Masala
Progress: 219/250
============================================================

Searching image for: Boiled Egg Bhurji Mushroom Masala...
Trying image 1...
Blur score (higher is sharper): 242.90
[ACCEPTED] Image 1 passed quality check.
Original size: (768, 1152)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Boiled Egg Bhurji Mushroom Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.36 MB
SUCCESS: 220/250

[357] SKIPPED:
Veg Burnt Chilli Garlic Fried Rice

[358] SKIPPED:
Veg Dum Biryani

============================================================
PROCESSING
Food: Chicken Liver Oil Fry Malai Kofta
Progress: 220/250
============================================================

Searching image for: Chicken Liver Oil Fry Malai Kofta...
Trying image 1...
Blur score (higher is sharper): 62.86
[REJECTED] Image 1 is too blurry.
Trying image 2...
Blur score (higher is sharper): 327.72
[ACCEPTED] Image 2 passed quality check.
Original size: (686, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Liver Oil Fry Malai Kofta.jpg
Final size: 1800 × 1200 pixels
File size: 0.32 MB
SUCCESS: 221/250

============================================================
PROCESSING
Food: Chicken 65
Progress: 221/250
============================================================

Searching image for: Chicken 65...
Trying image 1...
Blur score (higher is sharper): 609.16
[ACCEPTED] Image 1 passed quality check.
Original size: (600, 600)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken 65.jpg
Final size: 1800 × 1200 pixels
File size: 0.32 MB
SUCCESS: 222/250

============================================================
PROCESSING
Food: Mutton Kadai
Progress: 222/250
============================================================

Searching image for: Mutton Kadai...
Trying image 1...
Blur score (higher is sharper): 531.86
[ACCEPTED] Image 1 passed quality check.
Original size: (800, 800)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Mutton Kadai.jpg
Final size: 1800 × 1200 pixels
File size: 0.34 MB
SUCCESS: 223/250

============================================================
PROCESSING
Food: Veg Keema Masala
Progress: 223/250
============================================================

Searching image for: Veg Keema Masala...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 78.95
[REJECTED] Image 2 is too blurry.
Trying image 3...
Blur score (higher is sharper): 891.12
[ACCEPTED] Image 3 passed quality check.
Original size: (1160, 585)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Keema Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.48 MB
SUCCESS: 224/250

============================================================
PROCESSING
Food: Chicken Kadai
Progress: 224/250
============================================================

Searching image for: Chicken Kadai...
Trying image 1...
Blur score (higher is sharper): 755.22
[ACCEPTED] Image 1 passed quality check.
Original size: (600, 400)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Kadai.jpg
Final size: 1800 × 1200 pixels
File size: 0.38 MB
SUCCESS: 225/250

[364] SKIPPED:
Veg Manchurian Noodles

============================================================
PROCESSING
Food: Chicken Hunan Chilli Dry Chicken Tawa Fry
Progress: 225/250
============================================================

Searching image for: Chicken Hunan Chilli Dry Chicken Tawa Fry...
Trying image 1...
Blur score (higher is sharper): 296.92
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Hunan Chilli Dry Chicken Tawa Fry.jpg
Final size: 1800 × 1200 pixels
File size: 0.45 MB
SUCCESS: 226/250

============================================================
PROCESSING
Food: Honey Chilli Potato
Progress: 226/250
============================================================

Searching image for: Honey Chilli Potato...
Trying image 1...
Blur score (higher is sharper): 1258.76
[ACCEPTED] Image 1 passed quality check.
Original size: (1200, 1200)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Honey Chilli Potato.jpg
Final size: 1800 × 1200 pixels
File size: 0.55 MB
SUCCESS: 227/250

============================================================
PROCESSING
Food: Chicken Keema Masala
Progress: 227/250
============================================================

Searching image for: Chicken Keema Masala...
Trying image 1...
Blur score (higher is sharper): 301.10
[ACCEPTED] Image 1 passed quality check.
Original size: (720, 1080)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Keema Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.40 MB
SUCCESS: 228/250

============================================================
PROCESSING
Food: Chicken Afghani Egg 65
Progress: 228/250
============================================================

Searching image for: Chicken Afghani Egg 65...
Trying image 1...
Blur score (higher is sharper): 1417.84
[ACCEPTED] Image 1 passed quality check.
Original size: (2048, 1365)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Afghani Egg 65.jpg
Final size: 1800 × 1200 pixels
File size: 0.60 MB
SUCCESS: 229/250

============================================================
PROCESSING
Food: Paneer 65
Progress: 229/250
============================================================

Searching image for: Paneer 65...
Trying image 1...
Blur score (higher is sharper): 224.34
[ACCEPTED] Image 1 passed quality check.
Original size: (1536, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer 65.jpg
Final size: 1800 × 1200 pixels
File size: 0.45 MB
SUCCESS: 230/250

[370] SKIPPED:
Chicken Peshawari

============================================================
PROCESSING
Food: Chicken Reshmi Kebab Chicken Pasta Salad
Progress: 230/250
============================================================

Searching image for: Chicken Reshmi Kebab Chicken Pasta Salad...
Trying image 1...
Blur score (higher is sharper): 585.76
[ACCEPTED] Image 1 passed quality check.
Original size: (768, 768)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Reshmi Kebab Chicken Pasta Salad.jpg
Final size: 1800 × 1200 pixels
File size: 0.39 MB
SUCCESS: 231/250

============================================================
PROCESSING
Food: Veg Peshawari
Progress: 231/250
============================================================

Searching image for: Veg Peshawari...
Trying image 1...
[SKIPPED] Image 1 failed: HTTPSConnectionPool(host='www.kamat.ae', port=443): Max retries exceeded with url: /wp-content/uploads/2021/09/Veg.-Peshawari-768x469.jpg (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
Trying image 2...
Blur score (higher is sharper): 575.67
[ACCEPTED] Image 2 passed quality check.
Original size: (1280, 720)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Peshawari.jpg
Final size: 1800 × 1200 pixels
File size: 0.47 MB
SUCCESS: 232/250

[373] SKIPPED:
Mutton Manchow Soup

============================================================
PROCESSING
Food: Egg Noodles
Progress: 232/250
============================================================

Searching image for: Egg Noodles...
Trying image 1...
Blur score (higher is sharper): 256.88
[ACCEPTED] Image 1 passed quality check.
Original size: (626, 417)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Egg Noodles.jpg
Final size: 1800 × 1200 pixels
File size: 0.18 MB
SUCCESS: 233/250

============================================================
PROCESSING
Food: Veg Seekh Kebab
Progress: 233/250
============================================================

Searching image for: Veg Seekh Kebab...
Trying image 1...
Blur score (higher is sharper): 117.91
[ACCEPTED] Image 1 passed quality check.
Original size: (2000, 1335)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Veg Seekh Kebab.jpg
Final size: 1800 × 1200 pixels
File size: 0.35 MB
SUCCESS: 234/250

[376] SKIPPED:
Veg Biryani

[377] SKIPPED:
Veg Handi

[378] SKIPPED:
Veg Kadai

[379] SKIPPED:
Chicken Lollipop Gravy

============================================================
PROCESSING
Food: Chicken Thai Pei
Progress: 234/250
============================================================

Searching image for: Chicken Thai Pei...
Trying image 1...
Blur score (higher is sharper): 2377.96
[ACCEPTED] Image 1 passed quality check.
Original size: (600, 445)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Thai Pei.jpg
Final size: 1800 × 1200 pixels
File size: 0.36 MB
SUCCESS: 235/250

============================================================
PROCESSING
Food: Chicken Manchurian Gravy
Progress: 235/250
============================================================

Searching image for: Chicken Manchurian Gravy...
[ERROR] Search failed for Chicken Manchurian Gravy: error sending request for url (https://duckduckgo.com/?q=Chicken+Manchurian+Gravy+dish+restaurant+high+quality+photo) > operation timed out
[FAILED] No suitable image found for Chicken Manchurian Gravy

============================================================
PROCESSING
Food: Chicken Malai Kebab Cremote Chicken Pasta
Progress: 235/250
============================================================

Searching image for: Chicken Malai Kebab Cremote Chicken Pasta...
Trying image 1...
Blur score (higher is sharper): 1553.90
[ACCEPTED] Image 1 passed quality check.
Original size: (179, 156)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Malai Kebab Cremote Chicken Pasta.jpg
Final size: 1800 × 1200 pixels
File size: 0.20 MB
SUCCESS: 236/250

[383] SKIPPED:
Cream of Tomato Soup

[384] SKIPPED:
Chicken Hyderabadi

============================================================
PROCESSING
Food: Paneer Hyderabadi Biryani Lucknow Chicken Biryani
Progress: 236/250
============================================================

Searching image for: Paneer Hyderabadi Biryani Lucknow Chicken Biryani...
Trying image 1...
Blur score (higher is sharper): 2352.54
[ACCEPTED] Image 1 passed quality check.
Original size: (1266, 1266)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Paneer Hyderabadi Biryani Lucknow Chicken Biryani.jpg
Final size: 1800 × 1200 pixels
File size: 0.63 MB
SUCCESS: 237/250

============================================================
PROCESSING
Food: Chicken Masala
Progress: 237/250
============================================================

Searching image for: Chicken Masala...
Trying image 1...
Blur score (higher is sharper): 251.50
[ACCEPTED] Image 1 passed quality check.
Original size: (1024, 1024)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Masala.jpg
Final size: 1800 × 1200 pixels
File size: 0.41 MB
SUCCESS: 238/250

[387] SKIPPED:
Chicken Manchurian Soup

[388] SKIPPED:
Veg Chowmein

============================================================
PROCESSING
Food: Chicken Schezwan Noodles
Progress: 238/250
============================================================

Searching image for: Chicken Schezwan Noodles...
Trying image 1...
[SKIPPED] Image 1: not a valid image
Trying image 2...
Blur score (higher is sharper): 555.75
[ACCEPTED] Image 2 passed quality check.
Original size: (1000, 665)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Schezwan Noodles.jpg
Final size: 1800 × 1200 pixels
File size: 0.41 MB
SUCCESS: 239/250

[390] SKIPPED:
Mutton Lucknow Biryani

============================================================
PROCESSING
Food: Hot and Sour Chicken Soup Lemon Rice
Progress: 239/250
============================================================

Searching image for: Hot and Sour Chicken Soup Lemon Rice...
Trying image 1...
[SKIPPED] Image 1 failed: HTTPSConnectionPool(host='cookwithsavory.com', port=443): Max retries exceeded with url: /wp-content/uploads/2025/11/spicy-hot-and-sour-chicken-soup_1_U1.webp (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1028)')))
Trying image 2...
Blur score (higher is sharper): 1126.36
[ACCEPTED] Image 2 passed quality check.
Original size: (896, 1344)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Hot and Sour Chicken Soup Lemon Rice.jpg
Final size: 1800 × 1200 pixels
File size: 0.54 MB
SUCCESS: 240/250

============================================================
PROCESSING
Food: Chicken Oily Fry
Progress: 240/250
============================================================

Searching image for: Chicken Oily Fry...
Trying image 1...
Blur score (higher is sharper): 497.64
[ACCEPTED] Image 1 passed quality check.
Original size: (626, 353)
Processed size: (1800, 1200)
[PROCESSED & SAVED] processed_images\Chicken Oily Fry.jpg
Final size: 1800 × 1200 pixels
File size: 0.26 MB
SUCCESS: 241/250

============================================================

IndexError: At least one sheet must be visible

In [40]:
import os

processed_folder = "processed_images"

files = [
    f for f in os.listdir(processed_folder)
    if f.lower().endswith(".jpg")
]

print("Processed images:", len(files))

Processed images: 179

In [43]:
import os
import cv2
import pandas as pd

def create_final_report(
    processed_dir="processed_images",
    report_dir="reports"
):

    os.makedirs(report_dir, exist_ok=True)

    results = []

    image_files = [
        f for f in os.listdir(processed_dir)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    print(f"Images found: {len(image_files)}")

    for index, filename in enumerate(image_files, start=1):

        image_path = os.path.join(
            processed_dir,
            filename
        )

        img = cv2.imread(image_path)

        if img is None:
            results.append({
                "image_name": filename,
                "width": None,
                "height": None,
                "file_size_mb": None,
                "sharpness_score": None,
                "status": "INVALID_IMAGE"
            })
            continue

        height, width = img.shape[:2]

        gray = cv2.cvtColor(
            img,
            cv2.COLOR_BGR2GRAY
        )

        sharpness = cv2.Laplacian(
            gray,
            cv2.CV_64F
        ).var()

        file_size_mb = (
            os.path.getsize(image_path)
            / (1024 * 1024)
        )

        if (
            width == 1800
            and height == 1200
            and file_size_mb <= 10
        ):
            status = "VALID"
        else:
            status = "CHECK_REQUIRED"

        results.append({
            "image_name": filename,
            "width": width,
            "height": height,
            "file_size_mb": round(file_size_mb, 2),
            "sharpness_score": round(sharpness, 2),
            "status": status
        })

    report_df = pd.DataFrame(results)

    report_path = os.path.join(
        report_dir,
        "final_image_quality_report.xlsx"
    )

    report_df.to_excel(
        report_path,
        index=False
    )

    valid_count = (
        report_df["status"] == "VALID"
    ).sum()

    check_count = (
        report_df["status"] == "CHECK_REQUIRED"
    ).sum()

    invalid_count = (
        report_df["status"] == "INVALID_IMAGE"
    ).sum()

    print("\n" + "=" * 50)
    print("FINAL IMAGE REPORT")
    print("=" * 50)

    print(f"Total images : {len(report_df)}")
    print(f"Valid        : {valid_count}")
    print(f"Check needed : {check_count}")
    print(f"Invalid      : {invalid_count}")

    print(f"\nReport saved to:")
    print(report_path)

    return report_df

In [44]:
final_report = create_final_report()

Images found: 250

IndexError: At least one sheet must be visible

In [1]:
import os
import cv2
import pandas as pd

processed_dir = "processed_images"
report_dir = "reports"

os.makedirs(report_dir, exist_ok=True)

results = []

image_files = [
    f for f in os.listdir(processed_dir)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Images found:", len(image_files))

for filename in image_files:

    image_path = os.path.join(
        processed_dir,
        filename
    )

    img = cv2.imread(image_path)

    if img is None:
        results.append({
            "image_name": filename,
            "width": None,
            "height": None,
            "file_size_mb": None,
            "sharpness_score": None,
            "status": "INVALID_IMAGE"
        })
        continue

    height, width = img.shape[:2]

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2GRAY
    )

    sharpness = cv2.Laplacian(
        gray,
        cv2.CV_64F
    ).var()

    file_size_mb = (
        os.path.getsize(image_path)
        / (1024 * 1024)
    )

    if (
        width == 1800
        and height == 1200
        and file_size_mb <= 10
    ):
        status = "VALID"
    else:
        status = "CHECK_REQUIRED"

    results.append({
        "image_name": filename,
        "width": width,
        "height": height,
        "file_size_mb": round(file_size_mb, 2),
        "sharpness_score": round(sharpness, 2),
        "status": status
    })

final_report = pd.DataFrame(results)

print("\nTotal:", len(final_report))
print("\nStatus:")
print(final_report["status"].value_counts())

C:\Users\Bharg\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Images found: 250

Total: 250

Status:
status
VALID    250
Name: count, dtype: int64

In [2]:
from openpyxl import Workbook
import os

report_path = os.path.join(
    "reports",
    "final_image_quality_report.xlsx"
)

wb = Workbook()
ws = wb.active
ws.title = "Image Quality Report"

headers = [
    "image_name",
    "width",
    "height",
    "file_size_mb",
    "sharpness_score",
    "status"
]

ws.append(headers)

# Add the data
for row in final_report.itertuples(index=False):
    ws.append(list(row))

# Save
wb.save(report_path)

print("Report successfully created!")
print(report_path)

Report successfully created!
reports\final_image_quality_report.xlsx

In [3]:
import os
import pandas as pd
from openpyxl import Workbook

# Load the original food list
food_list = load_and_clean_food_items(excel_file)

processed_dir = "processed_images"
report_dir = "reports"

os.makedirs(report_dir, exist_ok=True)

results = []

for food in food_list:

    original_name = food["original_name"]
    search_query = food["search_query"]

    clean_name = sanitize_filename(original_name)

    image_path = os.path.join(
        processed_dir,
        f"{clean_name}.jpg"
    )

    if not os.path.exists(image_path):
        continue

    matching_rows = final_report[
        final_report["image_name"] == f"{clean_name}.jpg"
    ]

    if len(matching_rows) > 0:

        row = matching_rows.iloc[0]

        results.append({
            "food_name": original_name,
            "search_query": search_query,
            "image_name": clean_name + ".jpg",
            "image_path": image_path,
            "width": row["width"],
            "height": row["height"],
            "file_size_mb": row["file_size_mb"],
            "sharpness_score": row["sharpness_score"],
            "status": row["status"]
        })


company_report = pd.DataFrame(results)

print("Food items matched:", len(company_report))

print("\nPreview:")
display(company_report.head(10))

NameError: name 'load_and_clean_food_items' is not defined

In [5]:
import pandas as pd
import re
import os
import cv2

excel_file = r"C:\Users\Bharg\Downloads\Assignment - Ai agent  - Sheet1.xlsx"
def load_and_clean_food_items(file_path):

    raw_df = pd.read_excel(
        file_path,
        header=None
    )

    header_row_idx = None

    for idx, row in raw_df.iterrows():

        row_values = (
            row.astype(str)
            .str.strip()
            .str.lower()
            .tolist()
        )

        if "item_name" in row_values:
            header_row_idx = idx
            break

    if header_row_idx is None:
        raise KeyError(
            "Could not locate 'item_name' in the Excel file."
        )

    df = pd.read_excel(
        file_path,
        header=header_row_idx
    )

    df.columns = (
        df.columns
        .astype(str)
        .str.strip()
        .str.lower()
    )

    raw_items = (
        df["item_name"]
        .dropna()
        .tolist()
    )

    cleaned_items = []

    for item in raw_items:

        name = str(item).strip()

        if not name:
            continue

        if name.lower() == "item_name":
            continue

        name = re.sub(
            r"\[.*?\]",
            "",
            name
        )

        name = re.sub(
            r"\(.*?\)",
            "",
            name
        )

        individual_items = re.split(
            r"[\r\n]+",
            name
        )

        for individual_item in individual_items:

            individual_item = individual_item.strip()

            if not individual_item:
                continue

            cleaned_items.append({
                "original_name": individual_item,
                "search_query": individual_item
            })

    return cleaned_items

In [6]:
food_list = load_and_clean_food_items(excel_file)

print("Food items found:", len(food_list))
print(food_list[:5])

Food items found: 420
[{'original_name': 'Chicken Tandoori', 'search_query': 'Chicken Tandoori'}, {'original_name': 'Veg Fried Rice', 'search_query': 'Veg Fried Rice'}, {'original_name': 'Chicken Biryani Boneless', 'search_query': 'Chicken Biryani Boneless'}, {'original_name': 'Butter Roti', 'search_query': 'Butter Roti'}, {'original_name': 'Paneer Tikka Masala', 'search_query': 'Paneer Tikka Masala'}]

In [7]:
processed_dir = "processed_images"

results = []

image_files = [
    f for f in os.listdir(processed_dir)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Images found:", len(image_files))

for filename in image_files:

    image_path = os.path.join(
        processed_dir,
        filename
    )

    img = cv2.imread(image_path)

    if img is None:
        continue

    height, width = img.shape[:2]

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2GRAY
    )

    sharpness = cv2.Laplacian(
        gray,
        cv2.CV_64F
    ).var()

    file_size_mb = (
        os.path.getsize(image_path)
        / (1024 * 1024)
    )

    status = (
        "VALID"
        if width == 1800
        and height == 1200
        and file_size_mb <= 10
        else "CHECK_REQUIRED"
    )

    results.append({
        "image_name": filename,
        "width": width,
        "height": height,
        "file_size_mb": round(file_size_mb, 2),
        "sharpness_score": round(sharpness, 2),
        "status": status
    })

final_report = pd.DataFrame(results)

print("\nImages verified:", len(final_report))
print("\nStatus:")
print(final_report["status"].value_counts())

Images found: 250

Images verified: 250

Status:
status
VALID    250
Name: count, dtype: int64

In [8]:
company_report_data = []

for food in food_list:

    original_name = food["original_name"]
    search_query = food["search_query"]

    clean_name = re.sub(
        r'[\\/*?:"<>|]',
        "",
        original_name
    ).strip()

    image_filename = clean_name + ".jpg"

    image_path = os.path.join(
        "processed_images",
        image_filename
    )

    if not os.path.exists(image_path):
        continue

    matching_rows = final_report[
        final_report["image_name"] == image_filename
    ]

    if len(matching_rows) == 0:
        continue

    row = matching_rows.iloc[0]

    company_report_data.append({
        "food_name": original_name,
        "search_query": search_query,
        "image_name": image_filename,
        "image_path": image_path,
        "width": row["width"],
        "height": row["height"],
        "file_size_mb": row["file_size_mb"],
        "sharpness_score": row["sharpness_score"],
        "status": row["status"]
    })

company_report = pd.DataFrame(company_report_data)

print("Food-image matches:", len(company_report))

display(company_report.head(10))

Food-image matches: 412

,food_name,search_query,image_name,image_path,width,height,file_size_mb,sharpness_score,status
0,Chicken Tandoori,Chicken Tandoori,Chicken Tandoori.jpg,processed_images\Chicken Tandoori.jpg,1800,1200,0.39,402.05,VALID
1,Veg Fried Rice,Veg Fried Rice,Veg Fried Rice.jpg,processed_images\Veg Fried Rice.jpg,1800,1200,0.27,22.77,VALID
2,Chicken Biryani Boneless,Chicken Biryani Boneless,Chicken Biryani Boneless.jpg,processed_images\Chicken Biryani Boneless.jpg,1800,1200,0.58,186.78,VALID
3,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800,1200,0.37,161.36,VALID
4,Paneer Tikka Masala,Paneer Tikka Masala,Paneer Tikka Masala.jpg,processed_images\Paneer Tikka Masala.jpg,1800,1200,0.42,183.26,VALID
5,Chicken Fried Rice,Chicken Fried Rice,Chicken Fried Rice.jpg,processed_images\Chicken Fried Rice.jpg,1800,1200,0.34,170.00,VALID
6,Veg Triple Schezwan Fried Rice,Veg Triple Schezwan Fried Rice,Veg Triple Schezwan Fried Rice.jpg,processed_images\Veg Triple Schezwan Fried Ric...,1800,1200,0.44,218.06,VALID
7,Roti,Roti,Roti.jpg,processed_images\Roti.jpg,1800,1200,0.37,161.36,VALID
8,Chicken Tandoori,Chicken Tandoori,Chicken Tandoori.jpg,processed_images\Chicken Tandoori.jpg,1800,1200,0.39,402.05,VALID
9,Dal Khichdi Tadka Chicken Triple Fried Rice,Dal Khichdi Tadka Chicken Triple Fried Rice,Dal Khichdi Tadka Chicken Triple Fried Rice.jpg,processed_images\Dal Khichdi Tadka Chicken Tri...,1800,1200,0.33,89.34,VALID

In [9]:
print("Total food records:", len(food_list))

print(
    "Unique food names:",
    len(set(food["original_name"] for food in food_list))
)

print(
    "Unique image files:",
    company_report["image_name"].nunique()
)

print(
    "Rows in company report:",
    len(company_report)
)

Total food records: 420
Unique food names: 258
Unique image files: 250
Rows in company report: 412

In [10]:
duplicates = company_report[
    company_report["food_name"].duplicated(keep=False)
].sort_values("food_name")

print("Duplicate food records:", len(duplicates))

display(duplicates.head(20))

Duplicate food records: 262

,food_name,search_query,image_name,image_path,width,height,file_size_mb,sharpness_score,status
73,Butter Garlic Naan,Butter Garlic Naan,Butter Garlic Naan.jpg,processed_images\Butter Garlic Naan.jpg,1800,1200,0.55,247.81,VALID
325,Butter Garlic Naan,Butter Garlic Naan,Butter Garlic Naan.jpg,processed_images\Butter Garlic Naan.jpg,1800,1200,0.55,247.81,VALID
85,Butter Naan,Butter Naan,Butter Naan.jpg,processed_images\Butter Naan.jpg,1800,1200,0.27,19.09,VALID
198,Butter Naan,Butter Naan,Butter Naan.jpg,processed_images\Butter Naan.jpg,1800,1200,0.27,19.09,VALID
295,Butter Naan,Butter Naan,Butter Naan.jpg,processed_images\Butter Naan.jpg,1800,1200,0.27,19.09,VALID
3,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800,1200,0.37,161.36,VALID
76,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800,1200,0.37,161.36,VALID
193,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800,1200,0.37,161.36,VALID
288,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800,1200,0.37,161.36,VALID
38,Chana Garlic Fry,Chana Garlic Fry,Chana Garlic Fry.jpg,processed_images\Chana Garlic Fry.jpg,1800,1200,0.32,17.14,VALID
187,Chana Garlic Fry,Chana Garlic Fry,Chana Garlic Fry.jpg,processed_images\Chana Garlic Fry.jpg,1800,1200,0.32,17.14,VALID
71,Chicken Banjara Kebab,Chicken Banjara Kebab,Chicken Banjara Kebab.jpg,processed_images\Chicken Banjara Kebab.jpg,1800,1200,0.30,28.77,VALID
105,Chicken Banjara Kebab,Chicken Banjara Kebab,Chicken Banjara Kebab.jpg,processed_images\Chicken Banjara Kebab.jpg,1800,1200,0.30,28.77,VALID
227,Chicken Banjara Kebab,Chicken Banjara Kebab,Chicken Banjara Kebab.jpg,processed_images\Chicken Banjara Kebab.jpg,1800,1200,0.30,28.77,VALID
301,Chicken Banjara Kebab,Chicken Banjara Kebab,Chicken Banjara Kebab.jpg,processed_images\Chicken Banjara Kebab.jpg,1800,1200,0.30,28.77,VALID
2,Chicken Biryani Boneless,Chicken Biryani Boneless,Chicken Biryani Boneless.jpg,processed_images\Chicken Biryani Boneless.jpg,1800,1200,0.58,186.78,VALID
194,Chicken Biryani Boneless,Chicken Biryani Boneless,Chicken Biryani Boneless.jpg,processed_images\Chicken Biryani Boneless.jpg,1800,1200,0.58,186.78,VALID
121,Chicken Butter Garlic,Chicken Butter Garlic,Chicken Butter Garlic.jpg,processed_images\Chicken Butter Garlic.jpg,1800,1200,0.44,97.40,VALID
261,Chicken Butter Garlic,Chicken Butter Garlic,Chicken Butter Garlic.jpg,processed_images\Chicken Butter Garlic.jpg,1800,1200,0.44,97.40,VALID
285,Chicken Carbonara Pasta,Chicken Carbonara Pasta,Chicken Carbonara Pasta.jpg,processed_images\Chicken Carbonara Pasta.jpg,1800,1200,0.34,266.82,VALID

In [11]:
missing_foods = []

for food in food_list:

    original_name = food["original_name"]

    clean_name = re.sub(
        r'[\\/*?:"<>|]',
        "",
        original_name
    ).strip()

    image_filename = clean_name + ".jpg"

    image_path = os.path.join(
        "processed_images",
        image_filename
    )

    if not os.path.exists(image_path):

        missing_foods.append({
            "food_name": original_name,
            "expected_image": image_filename
        })

missing_df = pd.DataFrame(missing_foods)

print("Food records without images:", len(missing_df))

display(missing_df)

Food records without images: 8

,food_name,expected_image
0,Mutton Pepper Soup,Mutton Pepper Soup.jpg
1,Chicken Hong Kong Fried Rice,Chicken Hong Kong Fried Rice.jpg
2,Chicken Manchurian Gravy,Chicken Manchurian Gravy.jpg
3,Chicken Jeera,Chicken Jeera.jpg
4,Paneer Kolhapuri Chicken Tandoor Masala,Paneer Kolhapuri Chicken Tandoor Masala.jpg
5,Aloo Matar,Aloo Matar.jpg
6,Paneer Pulao,Paneer Pulao.jpg
7,Chicken Cheese Garlic Balls,Chicken Cheese Garlic Balls.jpg

In [12]:

company_report_data = []

for food in food_list:

    original_name = food["original_name"]
    search_query = food["search_query"]

    clean_name = re.sub(
        r'[\\/*?:"<>|]',
        "",
        original_name
    ).strip()

    image_filename = clean_name + ".jpg"

    image_path = os.path.join(
        "processed_images",
        image_filename
    )

    # Image exists
    if os.path.exists(image_path):

        matching_rows = final_report[
            final_report["image_name"] == image_filename
        ]

        if len(matching_rows) > 0:

            row = matching_rows.iloc[0]

            company_report_data.append({
                "food_name": original_name,
                "search_query": search_query,
                "image_name": image_filename,
                "image_path": image_path,
                "width": row["width"],
                "height": row["height"],
                "file_size_mb": row["file_size_mb"],
                "sharpness_score": row["sharpness_score"],
                "status": row["status"]
            })

    else:

        company_report_data.append({
            "food_name": original_name,
            "search_query": search_query,
            "image_name": None,
            "image_path": None,
            "width": None,
            "height": None,
            "file_size_mb": None,
            "sharpness_score": None,
            "status": "IMAGE_NOT_AVAILABLE"
        })


company_report = pd.DataFrame(company_report_data)

print("Total food records:", len(company_report))

print("\nStatus:")
print(company_report["status"].value_counts())

display(company_report.head(10))

Total food records: 420

Status:
status
VALID                  412
IMAGE_NOT_AVAILABLE      8
Name: count, dtype: int64

,food_name,search_query,image_name,image_path,width,height,file_size_mb,sharpness_score,status
0,Chicken Tandoori,Chicken Tandoori,Chicken Tandoori.jpg,processed_images\Chicken Tandoori.jpg,1800.0,1200.0,0.39,402.05,VALID
1,Veg Fried Rice,Veg Fried Rice,Veg Fried Rice.jpg,processed_images\Veg Fried Rice.jpg,1800.0,1200.0,0.27,22.77,VALID
2,Chicken Biryani Boneless,Chicken Biryani Boneless,Chicken Biryani Boneless.jpg,processed_images\Chicken Biryani Boneless.jpg,1800.0,1200.0,0.58,186.78,VALID
3,Butter Roti,Butter Roti,Butter Roti.jpg,processed_images\Butter Roti.jpg,1800.0,1200.0,0.37,161.36,VALID
4,Paneer Tikka Masala,Paneer Tikka Masala,Paneer Tikka Masala.jpg,processed_images\Paneer Tikka Masala.jpg,1800.0,1200.0,0.42,183.26,VALID
5,Chicken Fried Rice,Chicken Fried Rice,Chicken Fried Rice.jpg,processed_images\Chicken Fried Rice.jpg,1800.0,1200.0,0.34,170.00,VALID
6,Veg Triple Schezwan Fried Rice,Veg Triple Schezwan Fried Rice,Veg Triple Schezwan Fried Rice.jpg,processed_images\Veg Triple Schezwan Fried Ric...,1800.0,1200.0,0.44,218.06,VALID
7,Roti,Roti,Roti.jpg,processed_images\Roti.jpg,1800.0,1200.0,0.37,161.36,VALID
8,Chicken Tandoori,Chicken Tandoori,Chicken Tandoori.jpg,processed_images\Chicken Tandoori.jpg,1800.0,1200.0,0.39,402.05,VALID
9,Dal Khichdi Tadka Chicken Triple Fried Rice,Dal Khichdi Tadka Chicken Triple Fried Rice,Dal Khichdi Tadka Chicken Triple Fried Rice.jpg,processed_images\Dal Khichdi Tadka Chicken Tri...,1800.0,1200.0,0.33,89.34,VALID

In [13]:
from openpyxl import Workbook
import os

os.makedirs("reports", exist_ok=True)

final_report_path = os.path.join(
    "reports",
    "company_image_processing_report.xlsx"
)

wb = Workbook()

ws = wb.active
ws.title = "Image Processing Report"

ws.append(list(company_report.columns))

# Add all 420 records
for row in company_report.itertuples(index=False):
    ws.append(list(row))

# Save the workbook
wb.save(final_report_path)

print("Final company report created!")
print(final_report_path)

Final company report created!
reports\company_image_processing_report.xlsx

In [14]:
print(
    "Report exists:",
    os.path.exists(final_report_path)
)

print(
    "Report location:",
    final_report_path
)

Report exists: True
Report location: reports\company_image_processing_report.xlsx